### ISSUE TITLE
Coding style

### ISSUE THREAD

**Issue by oxygens** [munificent/wren#100]
You are a book author, yet your coding style is lacking at least about new lines after each and every one line if.

For example:
  if (argc == 1) return runRepl(vm);

It looks as if you trying to save lines of code.
No offence, this is a bad habbit which produces nothing. Not even readability, on the contrary.

:)

**Comment by zeckalpha** [comment]
There is a consistent style for that. If there is no else clause and the consequent is a single line, use no newline. I find this more readable than the `return runRelpl(vm) if (argc == 1)` style Ruby has.

Please avoid ad hominem attacks.

See: https://github.com/munificent/wren/pull/96#discussion_r22768628

**Comment by munificent** [comment]
Yes, like @zeckalpha said, one-line `if` statements are OK.
