### ISSUE TITLE
source highlighting

### ISSUE THREAD

**Issue by torwart** [munificent/wren#107]
Because Wren is not _official_ supported on GitHub, why don't give the *.wren-Files an [attribute](http://git-scm.com/book/en/v2/Customizing-Git-Git-Attributes) so that *.wren-Files will highlighted? (like Dart, C or something like that)

Example would be like that:

```
builtin/*.wren -dart
example/* -dart
```

**Comment by zeckalpha** [comment]
Alternatively, make it an official GitHub language: https://github.com/github/linguist

**Comment by torwart** [comment]
@zeckalpha :+1: never have seen this

**Comment by lluchs** [comment]
I've created a simple syntax definition for vim: https://github.com/lluchs/vim-wren

The only special thing it does right now is highlighting method definitions: ![code snippet](https://i.imgur.com/6fOiYVx.png)

**Comment by torwart** [comment]
@lluchs 
Looks very nice. I also currently work on a Syntax definition for Sublime Text. But the highlighting on GitHub would be better, currently it looks bad and only like *rich text*.

**Comment by munificent** [comment]
Highlighting them as Dart is a total hack. I picked it because Dart has C-based syntax and a `var` keyword. Scala works pretty well too. At some point, though, real syntax highlighting for the various editors and stuff would be great.

That Vim one looks nice, @lluchs!

**Comment by brandly** [comment]
In [/github/linguist](https://github.com/github/linguist), it says

> In most cases we prefer that each new file extension be in use in hundreds of repositories before supporting them in Linguist.

is there an index of programs written in Wren? Could we use the project wiki for this?

(mostly I just want to see more Wren examples)

**Comment by munificent** [comment]
> is there an index of programs written in Wren?

Not that I know of.

> Could we use the project wiki for this?

I like the idea of documenting this, but I think the wiki probably isn't the best place. GitHub doesn't (as far as I know) have any support for pull requests for wiki pages, so those (despite the name) are harder to contribute to than regular files in the repo.

Since the rest of the docs are under doc/, how about we just start adding more projects to doc/community.md?

**Comment by bjorn** [comment]
> GitHub doesn't (as far as I know) have any support for pull requests for wiki pages, so those (despite the name) are harder to contribute to than regular files in the repo.

Well, of course since wiki's can be edited by anyone, there is no real need for a pull request mechanism. But it does make edits more cumbersome to review. I see Wren has an empty wiki at the moment, and I'd just thought I'd mention that it can be disabled entirely in the repo settings when not wanted.

**Comment by munificent** [comment]
> Well, of course since wiki's can be edited by anyone

Oh, wow. I had no idea GitHub wikis were as permissive as Wikipedia. In that case, yeah, maybe we should use a wiki for a list of community Wren projects. Go for it.

**Comment by brandly** [comment]
Hey, Bob! I put up [a small list of programs](https://github.com/munificent/wren/wiki/Programs-Written-in-Wren) I know of. I'm probably leaving some out.

**Comment by bjorn** [comment]
@brandly Hmm, actually none of those are programs, they're all libraries. These things are already mentioned at https://munificent.github.io/wren/community.html. Maybe some of them should be added there.

**Comment by munificent** [comment]
Hopefully, the list of libraries will change pretty frequently, so maybe we should just yank them out of the community page and make that page link to the wiki?

**Comment by brandly** [comment]
@bjorn I was thinking of "libraries" as a subset of "programs," but I'm probably wrong. 

@munificent that's what I had in mind, but I haven't done anything about it yet :D

**Comment by horv** [comment]
Hi,
very (very...) simple syntax definition for [Atom][]: [language-wren][].

[atom]:https://atom.io
[language-wren]:https://github.com/horv/language-wren

**Comment by munificent** [comment]
Awesome!

**Comment by munificent** [comment]
I'm gonna go ahead and close this out since it looks like [the wiki](https://github.com/munificent/wren/wiki/Tools) has a handful of editor integrations listed.
