### ISSUE TITLE
Performance optimisation of readName method

### ISSUE THREAD

**Issue by Calamari** [munificent/wren#110]
Hi.

I just started to also read a bit of what is happening under the hood of wren and started with the compiler. It looks really straight forward. Kind of what I write when writing simple compilers. While reading, I stumbled upon line 529ff and thought that it could be done faster, right?

My C knowledge is a bit rusty (did that in school a bit, but that's really long ago), but the `readName` method seems to be doing much more then it has to. If you would read a `break token, you would still call the ìsKeyword`-method 15 times more often then you would have, when bailing out after matching the `break` if statement. Maybe something like:

```c
if (isKeyword(parser, "break")) type = TOKEN_BREAK;
else if (isKeyword(parser, "class")) type = TOKEN_CLASS;
else if (isKeyword(parser, "else")) type = TOKEN_ELSE;
…
```

Or using a switch statement or something?

**Comment by minirop** [comment]
switch statement isn't possible since you can only check 1 value against several integers.
But I also do think that "else" should be added.

**Comment by munificent** [comment]
Yeah, good call. Not sure what I was thinking there. :)
