### ISSUE TITLE
Attempting to build latest code as C++ fails in VS2013

### ISSUE THREAD

**Issue by RallyTronics** [munificent/wren#116]
After defining _CRT_SECURE_NO_WARNINGS to deal with all of the secure string BS that VS needs and setting WREN_COMPUTED_GOTO to 0,  I get the following errors:

Error	5	error C3861: 'snprintf': identifier not found
Error	22	error C2065: 'ssize_t' : undeclared identifier
Error	25	error C3861: 'getline': identifier not found

After some searching I see the above are not supported in VS.

If I set WREN_COMPUTED_GOTO to 1 it gets VERY unhappy.

Any thoughts?

**Comment by munificent** [comment]
The first three were me inadvertently using Linux-specific APIs. I just removed those, so try again and see if that helps.

The computed goto stuff just isn't supported in VS, so you'll have to leave that off. :(
