### ISSUE TITLE
System.print does not use overridden toString

### ISSUE THREAD

**Issue by Stephenmccaul** [munificent/wren#1188]
```
class OverrideToString {
    construct new(text){
        _text = text
    }

    toString(){ 
        return _text
    }
}

var o = OverrideToString.new("test")

System.print(o) //prints 'instance of OverrideToString' (not expected) Verified via debugger that this is calling the native object_toString rather than the overridden toString

System.print(o.toString()) //prints 'test' (as expected)
```

**Comment by mhermier** [comment]
Hi,
The method that you are trying to override is `toString` not `toString()`. `toString`conversion is a getter in `wren` not a regular method. The mix of getter/setter syntax and regular methods definitions can be quite confusing for beginners, so be carreful.

**Comment by Stephenmccaul** [comment]
This should really be in the String module doc.. and probably the Classes doc since its the first thing one would normally override.  (this would be a good example for overriding a getter method).

**Comment by mhermier** [comment]
Documentation is present in `Object`, maybe it should be augmented with an example.

**Comment by ruby0x1** [comment]
Thanks for the report @Stephenmccaul we can definitely improve the docs there.
