### ISSUE TITLE
WREN_PIN breaks under some optimizations

### ISSUE THREAD

**Issue by MarcoLizza** [munificent/wren#128]
Just reviewing the code. In the "wren_value.c" (lines 98 to 100) I guess there a not needed additional WREN_UNPIN "call". I'm a right?

**Comment by MarcoLizza** [comment]
Sorry, didn't noticed the first "pin". However, I'm getting some strange access violations when compiling in release mode in MSVC. Investigating.

**Comment by MarcoLizza** [comment]
It seems due to MSVC release-mode optimizations. For now I'm disabling it, but need further investigation.

**Comment by MarcoLizza** [comment]
Investigated a bit more.

Selectively disable optimization for "wrenPinObj" and "wrenUnpinObj" functions resolve the issue. This is quite odd (and scary).

I guess the MSVC2013U5 optimizer is getting a bit confused when inlining these functions.

**Comment by MarcoLizza** [comment]
I've been inspecting some more. To be honest, I'm not sure the `WREN_PIN` macro to be correct.

In its "body" an automatic variable is declared and its address is stored and used in the internal pin-list. We cannot expect it to be valid outside the `do{ } while(true)` scope. The `WrenPinnedObj` should be allocated dynamically, and freed upon unpinning.

I've change the two functions (and the macro and the signatures as well) as follows

```
void wrenPinObj(WrenVM* vm, Obj* obj)
{
  WrenPinnedObj *pinned = vm->reallocate(NULL, 0, sizeof(WrenPinnedObj));
  pinned->obj = obj;
  pinned->previous = vm->pinned;
  vm->pinned = pinned;
}

void wrenUnpinObj(WrenVM* vm)
{
  WrenPinnedObj *previous = vm->pinned->previous;
  vm->reallocate(vm->pinned, 0, 0);
  vm->pinned = previous;
}
```

*( these modifications render the `WREN_PIN` and `WREN_UNPIN` macros redundant, but I suggest to keep them for clarity )*

Is it correct or I'm a missing something?

**Comment by munificent** [comment]
Yeah, that was totally broken. I don't know what I was thinking there. :open_mouth:

I want to avoid heap allocation here so I changed it to just have a little fixed-size array of temporary roots. I'd initially planned to expose the pinning API to embedders which means it needed to be more flexible, but since then I've tried to make the embedding API not require that. So, for now at least, a fixed-size array is fine.

**Comment by MarcoLizza** [comment]
So, at last, it wasn't a optimizer bug (phew!) but the optimizer brought it to our attention. Well, there's always a silver lining. ;)

Are you considering to use an array-based stack or keeping a dynamic list approach?

If you like, I can provide my fix in the MSVC pull-request (being related to the no-longer-presumed MSVC bug).
