### ISSUE TITLE
Wrong API argument indexing documentation

### ISSUE THREAD

**Issue by MarcoLizza** [munificent/wren#133]
Either the implementation or the documentation of the Wren API is wrong.

Apparently `wrenGetArgument*` functions uses (as expected) zero-based indexes (as documented). However, both the provided example "IO" library (see function `ioWriteString`) and experimental use show that they are one-based.

It seems that the zero-index is reserved for the receiver pointer, not the first argument.

Also, the `foreignCallNumArgs` field is reporting an argument over what expected.

**Comment by munificent** [comment]
> It seems that the zero-index is reserved for the receiver pointer, not the first argument.

Yes, from the perspective of the API, the receiver is just another argument.

> Also, the foreignCallNumArgs field is reporting an argument over what expected.

It's correct as far as I can tell but note again that it considers the receiver to be an argument. I'll clarify the docs.

**Comment by MarcoLizza** [comment]
I suspected it to be WAD, just the documentation was not so clear. Thanks for elaborating it!
