### ISSUE TITLE
`validateKey()` compile error on Linux

### ISSUE THREAD

**Issue by MarcoLizza** [munificent/wren#148]
Is was going to launch some regression benchmark on my Linux machine, and I spotted a compilation error introduced in the commit '0e6a904'.

More precisely, the `validateKey()` function when storing the allocate string to `args[0]`, no conversion is needed since the `wrenNewString()` function already returns a `Value` object.

**Comment by munificent** [comment]
Oops! I'm surprised that even compiled on Mac.

**Comment by MarcoLizza** [comment]
I'm surprised it compiled on MSC, too... 😛
