### ISSUE TITLE
Make strings "8-bit clean"

### ISSUE THREAD

**Issue by munificent** [munificent/wren#152]
Now that strings know their length in Wren, that means we (should!) no longer rely on `\0` as a terminator. That in turn would enable us to have that appear in the middle of a string. Lua calls this being "8-bit clean". Go [also supports this](http://blog.golang.org/strings).

Doing this would let users use strings for arbitrary immutable byte buffers, which seems useful to me. To support this, I think we mainly need:

* Syntax for putting a zero byte in a string literal. `\x0000` works, I think, but `\0` would be nice.
* Lots of tests for all of the existing string methods to ensure they do the right thing in the presence of zero bytes.

@MarcoLizza, is this something you'd be interested in taking a look at?

**Comment by MarcoLizza** [comment]
Yep! Fine by me!

**Comment by munificent** [comment]
Awesome, thanks! I figured this is probably more fun than poking around with internal number types. :)

**Comment by MarcoLizza** [comment]
Yep, I'm pretty confident it would be. ;)

Thank you, too.

**Comment by MarcoLizza** [comment]
For the records, I started working on it...

**Comment by munificent** [comment]
:+1:

**Comment by munificent** [comment]
Thanks, @MarcoLizza!

**Comment by MarcoLizza** [comment]
it's been a pleasure! :+1:
