### ISSUE TITLE
this in static method

### ISSUE THREAD

**Issue by zeckalpha** [munificent/wren#154]
~~~
> class Oops { static test { this }}
> IO.write(Oops.test)
wren(20308,0x7fff7b814310) malloc: *** error for object 0x7fe608d0008c: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
OopsAbort trap: 6
~~~

**Comment by zeckalpha** [comment]
Should a static method be able to reference the class? I want to have a static method that does this:

~~~
class BaseError {
  static call {
    Fiber.abort(this.name)  // where this is the class
  }
}

class NotImplementedError is BaseError {}
// ...
~~~

**Comment by gsmaverick** [comment]
What instance of the class would `this` be referring to? In my experience static methods typically don't have access to any of the instance-specific state of the class.

**Comment by MarcoLizza** [comment]
> Should a static method be able to reference the class?

Static methods should only be able to access static data. `this.name` is "correct" as long as is to be interpreted as `ThisClass.StaticField`.

**Comment by zeckalpha** [comment]
What about in inheriting classes?

**Comment by zeckalpha** [comment]
@gsmaverick no instance, just the class.

**Comment by MarcoLizza** [comment]
> What about in inheriting classes?

Could you please elaborate a bit? What do you mean?

Why should one need to use `this` to clarify he/she wants to access a class method/field when accessing them is the only thing possible in static methods?

**Comment by zeckalpha** [comment]
Should it only refer to the class where the method was defined or to the
inheriting class?

**Comment by MarcoLizza** [comment]
I think I'm getting your point, now.

I don't think static methods need to be inherited (Wren does not support this by design). Inheritance behaviour is strictly bound to instances, not classes, and I second this.

What's the use of inheriting a static method? If that's the case, probably there's something wrong in the program design.

Have you in mind a real scenario where static methods inheritance could be useful/necessary?

**Comment by zeckalpha** [comment]
It's another tool in the box of code reuse. Particularly, it allows for some metaprogramming based on the class name.

The example I gave above was a partial solution for the "Should exceptions raise strings or classes?" problem.

That's not quite the point of this ticket. I don't think Wren should give a malloc error.

**Comment by munificent** [comment]
Wren definitely should not crash! I can't repro the issue on my machine. Do you have any local changes?

`this` *is* allowed inside static methods. It refers to the object representing the class itself. When you invoke methods on it, you're invoking methods defined on the metaclass. (In other words, like @MarcoLizza says, you can call static methods on it.)

Static methods are not inherited in Wren so this can only access static methods defined on the class itself. That makes `this` inside static methods not *that* useful, but `this` is still allowed for consistency's sake.

**Comment by MarcoLizza** [comment]
> That makes this inside static methods not that useful, but this is still allowed for consistency's sake.

Coming from a long-lasting C++ experience, I quite frankly found that `this` in static methods is confusing. But I could be just a matter of preference and habit.

**Comment by munificent** [comment]
Yeah, I don't think it will get used often in practice anyway, so I don't think most people will notice. Those that *do* will eventually understand that it makes sense once they understand metaclasses (which I really need to get around to documenting).

**Comment by zeckalpha** [comment]
> Wren definitely should not crash! I can't repro the issue on my machine. Do you have any local changes?

Sorry missed that. Checking now against latest.

**Comment by zeckalpha** [comment]
Hmm seems to have gone away.
