### ISSUE TITLE
Move benchmark script into script/

### ISSUE THREAD

**Issue by munificent** [munificent/wren#166]
Most of the Python scripts for doing various stuff live in `script/` in the root directory, except for `run_bench`. While the benchmark scripts themselves should stay under `benchmark/`, it would nice to move the benchmark runner into `script/` like the others.

**Comment by MarcoLizza** [comment]
Will try and do this along with the string benchmarks if that's ok with you...

**Comment by munificent** [comment]
Sounds good to me! Just to let you know, I'll be traveling the next days, so I may be slow to respond to PRs. :)

**Comment by MarcoLizza** [comment]
Don't worry, in the next two days I'll be busy too (with parental stuff and kid related flu :P).

I started some benchmarks... there's some many language features I'm ending in profiling. :mag: 

I'll keep you posted.

**Comment by munificent** [comment]
> kid related flu :P

Me and one of my kids got sick while traveling too. :(

**Comment by MarcoLizza** [comment]
Darn! Hope you'll get well soon!

*(Wren development is flu-proof, as we all see)*
