### ISSUE TITLE
More infix operands?

### ISSUE THREAD

**Issue by MarcoLizza** [munificent/wren#171]
I was just wondering if it might be of some use adding some other commons infix operands, such as `^`, `<<` and `>>`.

The current bitwise toolbox lacks of the common XOR, LSH and RSH operations.

Although they can be obtained by means of the other bitwise operations and/or multiplications, it may be convenient to have them.

Also, the token itself could come handy for other (over-ridden) uses.

**Comment by munificent** [comment]
:+1: for those three operators. Stuff like self-assignment and `++` and `--` are trickier, but `^`, `<<`, and `>>` are just an oversight on my part.

**Comment by zeckalpha** [comment]
Would `++` and `--` be worth including? I find there's so many ambiguities around them that they cause more problems than good.

**Comment by MarcoLizza** [comment]
For their terseness, they are worth the effort. However, their most common use-case can be obtained with self-assignment operations (which I think should be introduced some time in the future).

By the way, I'm testing a draft addition of the missing bitwise operands. Pull-request will follow!

**Comment by munificent** [comment]
`++` and `--` are a bit harder (as are self-assignment operators), since they aren't semantically just a method call.
