### ISSUE TITLE
Removing element from List

### ISSUE THREAD

**Issue by jkleiser** [munificent/wren#176]
The docs at http://munificent.github.io/wren/lists.html#removing-elements says nothing about what kind of value that's returned from 'letters.removeAt(1)'. It should!
In my case I would have preferred a function that returned a new List with the one element removed, as this solution looks a bit cryptic:
var newLetters = letters[0..-1]
newLetters.removeAt(i)

**Comment by munificent** [comment]
Right now, `removeAt()` doesn't accept a range argument. When it does, it will return the list of removed elements like you suggest. With a single index argument, it returns the removed element. That's document now. :)

Thanks for the bug!
