### ISSUE TITLE
Execution speed compared to Dart

### ISSUE THREAD

**Issue by jkleiser** [munificent/wren#179]
I wanted to compare the execution speeds for a few of the benchmarks using Wren vs. Dart. To my surprise Dart seems to be much faster. While (on my Mac) Wren reports "elapsed: 0.288371" for the binary_trees.wren, my Dart version says "elapsed: 0.025769". I've also done the "fib" and "for". It's available here: http://folk.uio.no/jkleiser/wren/benchmark.zip
If you're interested, I could try porting a few more.

**Comment by munificent** [comment]
> To my surprise Dart seems to be much faster.

This shouldn't be a surprise. :)

Dart uses a very advanced JIT so it's going to be like an order of magnitude faster than Wren (or Ruby, Python, Lua, or other bytecode VMs).

If you compare Wren to most JS engines, you'll see the same results. It would be lovely to be as fast those, but getting there requires a *massively* more complex VM, and also means you can't be used in places like iOS and game consoles that disallow just-in-time compilation.
