### ISSUE TITLE
runFile segfault when lastSlash is null

### ISSUE THREAD

**Issue by szensk** [munificent/wren#181]
First try at wren and I tried the hello world. `./wren hello.wren`
which produces a segfault.
Then I tried `./wren -h`
which also produces a segfault.

Simple fix that worked for me:
```c
  char* lastSlash = strrchr(path, '/');
  if(lastSlash != NULL)
  {
  	rootDirectory = malloc(lastSlash - path + 2);
  	memcpy(rootDirectory, path, lastSlash - path + 1);
  	rootDirectory[lastSlash - path + 1] = '\0';
  }
```
Now I can run hello world. But maybe it breaks other things?

**Comment by munificent** [comment]
Oof, yeah. I broke that when I landed the new module stuff. :( Thanks for the bug report and the diff. I'll fix it as soon as I get a chance.
