### ISSUE TITLE
issues with numbers.

### ISSUE THREAD

**Issue by ghost** [munificent/wren#182]
representation for infinity is 1.#INF, not inf, which prevents some tests from passing.
also, the test in sqrt.wren that expects -0 gets nan instead.
using gcc 4.7.3 and 4.8.2, both with patches from strawberry perl.

**Comment by munificent** [comment]
> representation for infinity is 1.#INF, not inf

Do you mean the string representation here?

**Comment by halveksin** [comment]
yes, it's the string value from the %g format.
i fixed it by checking if the double value equals the infinity constant and returned the proper string.

**Comment by munificent** [comment]
> i fixed it by checking if the double value equals the infinity constant and returned the proper string.

Do you handle negative infinity too? Want to send me a pull request? Apparently, this is a corner of the C standard library that's implementation defined, so it would be nice for Wren to handle it (like it does NaN, for similar reasons).

**Comment by munificent** [comment]
I'm not sure when it landed, but it looks like we do handle printing `infinity` and `-infinity` correctly. I don't know if there are other changes we need to make, so I'll close this out for now. If the sqrt thing is still an issue, let me know.
