### ISSUE TITLE
REPL is broken after module addition

### ISSUE THREAD

**Issue by gsmaverick** [munificent/wren#184]
The REPL is now broken after modules were added because a new "main module" is being created for every line that's interpreted from the console. The following REPL session demonstrates the issue:

```
> var x = [1,2]
> var y = [1,2]
> x == y
[main line 1] Error at 'x': Undefined variable.
[main line 1] Error at 'y': Undefined variable.
```

**Comment by munificent** [comment]
Yup! Should be fixed by: https://github.com/munificent/wren/commit/422801a64a04eba9e7f57f9de53bb25e1ca991c9
