### ISSUE TITLE
How to open and read from a given file?

### ISSUE THREAD

**Issue by jkleiser** [munificent/wren#188]
I'm looking for a way to open and read lines from a given file, and on EOF, close the file, and write some results to another file. Are the necessary functions not implemented yet?

**Comment by zeckalpha** [comment]
See #87 and #108.

This may be beyond the scope of wren proper, but not wren-io.

**Comment by munificent** [comment]
Yup, what @zeckalpha said. Wren (the core language) doesn't have a built-in IO library.
