### ISSUE TITLE
[website] some links do not work under IE

### ISSUE THREAD

**Issue by PavelVozenilek** [munificent/wren#204]
I use IE 11 under Win7 64 bit. Some links inside the right side menu column cannot be clicked (e.g. Getting Started). Few work (e.g. Control Flow). Mouse cursor does not see them as links (doesn't switch to Hand symbol). I have to list all pages via Google's site: command, then I read them w/o any problem.

I do not have this problem with any other site.

**Comment by munificent** [comment]
That's really strange. As far as I know, there's nothing unusual about the links. Do links in the main column work? If you resize the window really small (to force a mobile layout) do the side bar links start working?

**Comment by PavelVozenilek** [comment]
1. Yes, links in main column work.
2. If I resize the window to be very small the links suddenly work.
3. One possible reason could be that I said browser to use larger than usual font (125%).

On Chrome everything works.

**Comment by Nelarius** [comment]
Bizarre, I just tested the website on IE11 on windows 8 and noticed the same thing. Links in sidebar mostly don't work. Never seen this happen before. This is using regular font size, btw.

I think the solution here might be to use a non-IE browser :P

**Comment by munificent** [comment]
That's so bizarre. I have no way of reproducing this. If you feel like being a web developer and trying to debug my HTML/CSS you're definitely welcome to. Otherwise... I don't know what to do. Thanks, IE.

**Comment by TZAdvantage** [comment]
The reason, and i know this sounds bizar is that IE is following the latest standards and browsers like Chrome do not. I do web development on a daily and profession basis so i am aware of these browser incompatibilities and they are numerous and getting worse!
The <nav> tag is before the <main> tag which means the navigation is under the main content. The links that do work are the ones that line up with an empty line in the main body. Add a 'float:left;" to main to force main also to flow and then it will work.

**Comment by RickGlimmer** [comment]
The reason, and i know this sounds bizarre :) is that IE is following the latest standards and browsers like Chrome do not. Browser incompatibilities are numerous and getting worse! Our standard approach is now to develop in IE11 and then fix stuff for the other browser like Firefox (just a little), Chrome (much worse) and Webkit (terrible).
The <nav> tag is before the <main> tag which means the navigation is under the main content.
A div and p are both default display:block which means it will take the full width. Floating main will fix it;
The links that do work are the ones that line up with an empty line (in between the P tags) in the main body. Add a 'float:left;" to main to force main also to flow or add "display:inline-block;" to the <main> tag.

One 'rule' to follow is that when you float a tag, also float all the other tags within the same parent.
Then use a clear to make sure normal flow is restored;
(reposted it with the right account :) )

I will have a go at fixing this soon.

**Comment by bjorn** [comment]
@RickGlimmer Looks like you should run `make docs` for this, since that includes the site. Or run `./script/generate_docs.py` directly.

**Comment by munificent** [comment]
> And if you are iterating, ./script/generate_docs.py --watch looks really useful. :-)

Even better:

```
$ make watchdocs
```

:)

**Comment by RickGlimmer** [comment]
Aha! Got it. 
I will start on it.

**Comment by RickGlimmer** [comment]
Well, that did not really work well.
It seems there are a lot of dependencies that need to be installed.
I don't mind installing python. I installed version 3.4.3.
I use windows 8.1.
Which other tools do i need to install.
I can find markdown and sass in the generate_docs.py file. Which versions would be best.
Any other dependencies that the dependencies depend on.:)

**Comment by bjorn** [comment]
I already have some Python packages installed, but I just needed to add `markdown`. If you have `pip` available on the command line, it's as easy as:
```
sudo pip install markdown
```
I never looked into whether `pip` works on Windows, though.

**Comment by RickGlimmer** [comment]
I have got markdown to work. Sass not yet.

**Comment by munificent** [comment]
Sorry for the undocumented steps to get the site building. When I first started hacking on Wren, it wasn't something I really thought a lot of people who be chipping in on. My mistake!

One thing you can do that would be really helpful since you *are* going through this process is to take some notes on what you had to do to get it all working. We can add those to the repo so that others can more easily follow in your footsteps.

In particular, this setup is a good bit more difficult on Windows since Linux and Macs tend to have Python and Ruby already installed.

**Comment by RickGlimmer** [comment]
The fix is easy. Just add 'float:left;' to main tag.
I tried it out on the gh-pages branch and that was the only fix needed.:)
I skipped installing sass after a few tries.The python version is not working properly and i do need to keep my system clean from programs i never use. So no ruby.
A pull request has been send.

**Comment by zeckalpha** [comment]
Do not use `sudo` in a `pip install` if you can't help it.

**Comment by bjorn** [comment]
> Do not use sudo in a pip install if you can't help it.

Right, I always seem to mess up my system that way. It's just that I often hit problems trying to install things in my home directory. However, right now I can't say whether this was using `pip`, `gem` or whatever package it was. If only there was just one package management system to rule them all. :-)

**Comment by munificent** [comment]
> A div and p are both default display:block which means it will take the full width. Floating main will fix it;
The links that do work are the ones that line up with an empty line (in between the P tags) in the main body. Add a 'float:left;" to main to force main also to flow or add "display:inline-block;" to the tag.

That's weird. Given that `<main>` *has* an explicit width, I would expect that to take precedence over the default full-width behavior. That's certainly how it works on Chrome and Firefox.

But, if that fixes IE, great. Thanks!
