### ISSUE TITLE
IO.read reaching EOF

### ISSUE THREAD

**Issue by soveran** [munificent/wren#207]
Should IO.read return an empty string in that case? It's marked as a TODO in the code, and locally I've been using a patch that returns "" in that case.

**Comment by munificent** [comment]
You know, I honestly don't know. I didn't implement `read` and haven't put much thought into it.

If I had to pick, I'd probably say it should return `null`? That way you can distinguish between "no more input *ever again*" and "no input *right now*"?

But, I'm not sure if that distinction is even meaningful. If `fgets` returns zero bytes, can it ever later have more input?

What do you think?

**Comment by soveran** [comment]
Yes, `null` works better :-)

**Comment by munificent** [comment]
OK, throw me a pull request! :)

**Comment by soveran** [comment]
Done. I couldn't find any reference in the code to what the desired style should be in this case, so let me know (or change it at will) if it doesn't match your taste.
