### ISSUE TITLE
Fields are not inherited

### ISSUE THREAD

**Issue by b01dface** [munificent/wren#237]
The website specifies all fields are protected, however the following test proves otherwise:

```
class A {
	new {
		_a = 5
	}

	printFromA { _a }
}

class B is A {
	new {
		super
		_a = 9
	}

	printFromB { _a }
}

var x = new B

IO.print(x.printFromB) // prints 9
IO.print(x.printFromA) // prints 5
```

If all fields are protected should both lines print 9?

**Comment by munificent** [comment]
Oops! The docs are wrong. Fields are private. They are inherited (a derived object will have the fields of its base class), but they can only be accessed from within methods in the base class.
