### ISSUE TITLE
segfault on IO.print(new List)

### ISSUE THREAD

**Issue by zeckalpha** [munificent/wren#25]
~~~
> IO.print(new List)
zsh: segmentation fault  ./wren
~~~

**Comment by tamc** [comment]
Can't replicate this as of 84ead3bb18135657fb276ae09459e3be4717764d OSX Yosemite

    > IO.print(new List)
    []
    > var x = new List
    > x.add(1)
    >

Is it fixed?

**Comment by zeckalpha** [comment]
I'll try this out today.

**Comment by zeckalpha** [comment]
It works for me now.

**Comment by munificent** [comment]
\o/
