### ISSUE TITLE
Add a page for "Wren community" stuff

### ISSUE THREAD

**Issue by EvanHahn** [munificent/wren#257]
Would love a place on the site for "here are some Wren libraries" and "here are some integrations for editors".

Speaking of, here are some Wren libraries:

- [wren-test](https://github.com/gsmaverick/wren-test)
- [Please](https://github.com/EvanHahn/wren-please)
- [wren-colors](https://github.com/gsmaverick/wren-colors)
- [wren-vector3d](https://github.com/EvanHahn/wren-vector3d)

Here are some FFI bindings:

- [Rust: tilpner/wren-sys](https://github.com/tilpner/wren-sys)
- [Rust: pwoolcoc/wren-sys](https://github.com/pwoolcoc/wren-sys)
- [Rust: pwoolcoc/wren-rs](https://github.com/pwoolcoc/wren-rs)

And here are some editor integrations:

- [Vim](https://github.com/lluchs/vim-wren)
- [Emacs](https://github.com/v2e4lisp/wren-mode.el)

**Comment by lluchs** [comment]
A page on the wiki might be best for this, as it allows everyone to add their libraries without waiting for a pull request.

**Comment by EvanHahn** [comment]
Agreed. What should that page look like?

**Comment by munificent** [comment]
This is a great idea! I'm up for putting it on the wiki here, or putting it on the main site. Either way works. Feel free to take a stab at it and send me a PR. :)
