### ISSUE TITLE
Running set example errors

### ISSUE THREAD

**Issue by hij1nx** [munificent/wren#266]
Freshly pulled from github, after running make...

```
./wren example/set.wren
WhereSequence does not implement '+(_)'.
[main line 91] in &(_)
[main line 110] in (script)
true
```

**Comment by bjorn** [comment]
Hrm, I didn't notice this example when I changed `Sequence.where` to be lazy rather that eagerly returning the computed list, which apparently the example Set class still relies on.

The example can be fixed by adding `.toList()` at the end of each call to `where` and the call to `map`.

**Comment by bjorn** [comment]
Note that this example is now quite bad since implementing a set should be much more efficient based on the `Map` class instead of the `List` class. So while it could be fixed up to run, it probably really needs a complete rewrite.

**Comment by munificent** [comment]
+1 for rewriting it to use a map.

**Comment by zeckalpha** [comment]
Yeah, I wrote that before Maps existed. Feel free to remove the file entirely, too.

**Comment by munificent** [comment]
Done!
