### ISSUE TITLE
REPL features

### ISSUE THREAD

**Issue by 0x00A** [munificent/wren#267]
Would you accept a pull request that added [`linenoise`](https://github.com/antirez/linenoise) to the REPL?

**Comment by bjorn** [comment]
I support the idea! :-)

**Comment by munificent** [comment]
Possibly! I'm definitely interested in better line editing in the REPL and linenoise is right up my alley. I'm OK with the REPL taking external dependencies. It's the embeddable VM library itself that I want to keep dependency-free.

At the same time, it depends on how hairy the integration ends up looking. Also, the REPL needs a lot of high level work eventually which will probably necessitate much of it being written in Wren. That may interfere with using linenoise. But we can probably cross that bridge when we come to it.

Feel free to send me a pull request and we'll see how it looks. Thanks!

**Comment by munificent** [comment]
Closing this out since it seems kind of stale. I'm still interested in a better REPL, though. :)
