### ISSUE TITLE
Suggestion: Have a reference for the IO object

### ISSUE THREAD

**Issue by sbrl** [munificent/wren#274]
Perhaps I have missed something, but while looking around I couldn't find a reference that told me what the IO object does. There may even be other objects out there that I don't even know exist.

I think that a reference for the IO object would be useful to newcomers to the language.

**Comment by bjorn** [comment]
Hmm, that is indeed a strange ommission. The Meta class is also undocumented, but this is easier to understand since it has only just been added.

In any case you can find all methods of the IO class over here for now:

https://github.com/munificent/wren/blob/master/builtin/io.wren

**Comment by sbrl** [comment]
Thanks!
That is very helpful :)

**Comment by sbrl** [comment]
I have submitted pull request #275 that includes my attempt at documenting the IO class. I took a look at the way the other classes were documented, and applied the same rules to the IO class.

On a side note I have also written a pseudo-random number generator (using the xor128 algorithm) in wren - just ask if you are interested :)

**Comment by munificent** [comment]
> I have submitted pull request #275 that includes my attempt at documenting the IO class.

Thank you! :D

**Comment by sbrl** [comment]
No problem :)

**Comment by munificent** [comment]
Fixed by https://github.com/munificent/wren/pull/275.
