### ISSUE TITLE
Written interview about Wren

### ISSUE THREAD

**Issue by unbalancedparentheses** [munificent/wren#287]
First of all sorry @munificent for using github issue, but I have not found any other better way to contact you. I am interviewing different programming language creators about the reasons why they have created the language, how they did it, what design choices they have faced, how it compares to other languages, etc.

For the moment I have only published only one interview with pretty good success and comments:
https://medium.com/indie-programming-languages

Let me know if you are interested in answering a small interview!

THANKS in advance

PS: Leave me a contact if you don't like to talk via github issues.

**Comment by munificent** [comment]
Sure, sounds like fun. You can email me at `robert` at `stuffwithstuff.com`. :)
