### ISSUE TITLE
generate_builtins.py produces invalid wren_core.c 

### ISSUE THREAD

**Issue by ppvk** [munificent/wren#289]
If you `make builtin`, lines 68-73 in `wren_core.c` look like this:

    "\n"
    "  isEmpty { iterate(null) ? false : true }
    \n"
    "
    \n"
    "  map(transformation) { new MapSequence(this, transformation) }\n"

You'll notice that some of the quotes and newlines are a bit off.
The compiler doesn't like that very much. :disappointed_relieved: 

I'm going to eat, and when I come back I'll poke around `generate_builtins` and see If I can fix it, as I need to generate the `wren_js.c` file for `wrenjs`.

**Comment by munificent** [comment]
I just noticed that too. I was in the middle of other things so I didn't fix it, but it just requires fixing the busted newline on `isEmpty` in core.wren.

**Comment by munificent** [comment]
Actually, scratch that. I *did* end up commiting a fix in https://github.com/munificent/wren/commit/d91c06d18b1b8ad31d9e99b7ef30af5c2effbf75. :)

**Comment by ppvk** [comment]
Awesome thanks!
