### ISSUE TITLE
Foreign classes

### ISSUE THREAD

**Issue by munificent** [munificent/wren#290]
Working on the libuv integration and adding a real standard library to the CLI has been really useful for fleshing out the embedding API for the VM. I'm starting to look at adding file IO. That means being able to open a file, read from it, then close it.

That in turn means I need a class in Wren, File, that has a reference to a file descriptor, a C native object. In addition, if the File object gets garbage collected, we need to ensure the file is closed. So I've got a good concrete use case in Wren for what Lua handles with userdata.

I think the requirements are:

* Create objects in Wren that store extra bytes of data defined and initialized in C.

* Access those bytes from within a foreign method.

* Provide a function that finalizes those bytes when the object is garbage collected.

Here's my proposal. This is just a rough sketch, so, assumming people like this, it may still change significantly once I start implementing it.

You can define a "foreign class", like so:

```
foreign class File {
  ...
}
```

It's just the `foreign` keyword before a class definition. A foreign class has a few restrictions:

* It cannot have any instance fields.
* It cannot declare a superclass. (The reverse is also true. You cannot subclass a foreign class.)

These ensure that the *only* data an instance of a foreign class needs to worry about is the external bytes managed by the embedder. A foreign class *may* have any of the following:

* Static methods and fields.
* Constructors, including a default one if no other constructors are declared.
* Instance methods, foreign or otherwise.

In other words, it's a full-featured class in all other respects.

### Foreign instances in the VM

Internally, an instance of a foreign class is not an `ObjInstance`, but is instead a:

```c
typedef struct
{
  Obj obj;
  size_t size;
  uint8_t[FLEXIBLE_ARRAY] data;
} ObjForeign;
```

In other words it's just a wrapper around an array of bytes. Since `obj` has a pointer to a `ObjClass`, the foreign instance *does* know its class.

### Compiling a foreign class

For the most part, foreign classes are compiled like regular classes. Aside from making sure that no fields are defined, methods and static methods are compiled normally. There are two differences:

* When emiting the class definition itself, a separate `CODE_FOREIGN_CLASS` opcode is used instead of `CODE_CLASS`.

* When compiling a constructor, `CODE_FOREIGN_CONSTRUCT` is emitted instead of `CODE_CONSTRUCT`.

### Interpreting `CODE_FOREIGN_CLASS`

A `CODE_FOREIGN_CLASS` instruction is handled similarly to a `CODE_METHOD` instruction for a foreign method. The VM invokes a `WrenBindForeignClassFn` function that the embedder provides to it, with a signature like so:

```c
WrenForeignClassData
bindForeignClass(WrenVM* vm, const char* module, const char* className);
```

The embedder implements this to return a struct containing two pointers:

```c
typedef struct
{
  WrenForeignMethodFn initialize;
  WrenForeignMethodFn finalize;
} WrenForeignClassData;
```

The `finalize` function is optional and can be `NULL`. The VM takes these two functions are stores them in the foreign class's method table with some magical names that can't be accessed from regular Wren code.

So now we have a foreign class with two foreign methods to create and destroy the embedder-managed external data.

### Interpreting `CODE_FOREIGN_CONSTRUCT`

Now that we have a class, we can use it. When a constructor for a foreign class is called, it executes a `CODE_FOREIGN_CONSTRUCT` instruction. That works similar to how a foreign method is invoked. In this case, though the foreign method is `initialize` function provided earlier.

The VM sets up the foreign call stack and then invokes that C function. Within the body of the function the embedding application is responsible for calling:

```c
void* wrenAllocateForeign(WrenVM* vm, size_t size);
```

This must be called exactly once. It tells the VM how many bytes of raw data the foreign object needs. In this function, Wren actually allocates the `ObjForeign` instance. Then it returns a pointer to the raw bytes that were allocated.

The embedder can then initialize those bytes however it wants.

### Accessing foreign data in other methods.

Inside other foreign methods, you can access the raw bytes of a foreign object using:

```
void* wrenGetArgumentForeign(WrenVM* vm, int index);
```

If the parameter to the foreign method at the given index is a foreign object, this returns a pointer to its bytes. Usually the index will be zero to get the foreign bytes on `this`, but you can do this to access data from any foreign parameter.

Of course, it's up to the embedder to ensure it only does this on objects of the correct foreign type and doesn't overwrite the wrong memory.

### Finalizing

If the foreign class defines a finalizer, it is stored in the class's method table. When the GC runs, if it frees a foreign object, it will look for that finalizer method. If it finds it, it invokes it before the object is freed.

(There are more optimal ways we can handle this using explicit finalizer lists, but this should be good enough for a first implementation.)

And that's it. What do you think?

**Comment by soveran** [comment]
It looks elegant :-)

**Comment by minirop** [comment]
Looks good to me!  👍

**Comment by IsaacWoods** [comment]
Looks great!

**Comment by verpeteren** [comment]
The `You cannot subclass a foreign class` sentence disturbed me at first, but on second thought: It probably keeps the language small and the implementation practical.

**Comment by munificent** [comment]
After some discussion on the mailing list, I'll probably relax that constraint a bit. Instead, we can allow a foreign class to have a base class, as long as it (transitively) does not declare any fields.

**Comment by munificent** [comment]
This is mostly working now as of https://github.com/munificent/wren/commit/48bdbc77459d443d21ca9157088d65bce49143f1. Still need to call finalizers from the GC, but it's getting there!

I did relax the restriction on subclassing. A foreign class can inherit from another class as long as that class (and its superclasses) don't declare any fields.

**Comment by munificent** [comment]
Now that finalizers are in (36f3059e483116b7eecf4c51cc89cbd9c1b7dcb6), I'm calling this done. Let me know if you run into any issues!

**Comment by PH0lder** [comment]
For those looking at this as a guide for implementation, there appears to have been some sort of later change that implemented the "slot" functions and thus removed some other functions, which includes `wrenAllocateForeign`.  Unfortunately, there are still some references in the wren.h and elsewhere that still reference this, which made it a real headscratcher for a while.  The correct function now appears to be `wrenSetSlotNewForeign`.
