### ISSUE TITLE
Use of src/vm/wren_common.h

### ISSUE THREAD

**Issue by ppearson** [munificent/wren#304]
The use of __builtin_unreachable()
in src/vm/wren_common.h

Is problematic for GCC versions before 4.5 as GCC 4.5 was the version which added support for this.

GCC 4.1 and 4.4 is still used quite heavily in certain industries (VFX in particular), and being slightly cheeky you do mention C99 compliance, which while technically true, does rely on a compiler specific built-in...

LLVM and ICC (version 2013.1 +) both support __builtin_unreachable.

I've got a hacky fix for the moment, but it would be great if this could be checked robustly.

**Comment by IsaacWoods** [comment]
We could (sort of) fix this with a little preprocessor magic:
``` c
#if (__GNUC__ >= 4 && __GNUC_MINOR__ >= 5)
__builtin_unreachable
#endif
```

**Comment by munificent** [comment]
> being slightly cheeky you do mention C99 compliance

Not cheeky at all. We definitely don't want to require any non-standard extensions. If Wren can detect that a platform supports it, it's fine to opt-in, but it still should still reliably fallback if not present. That's what we do, for example, with computed gotos.

@IsaacWoods, version conditions are notoriously hard to get right. That one would do the wrong thing in GCC 5.2. :) We'd want:

```c
#if (__GNUC__ > 4 || (__GNUC__ == 4 && __GNUC_MINOR__ >= 5))
```

In GCC <4.5, is there some other way to mark a chunk of code unreachable? If not, we could just remove the `UNREACHABLE` macro and use `ASSERT()` plus some nonsense return value, but I do like the readability and checking of the macro.

**Comment by ppearson** [comment]
I don't think there is implicitly - certainly not that will prevent return value warnings - if you want a warning/error printed out in this situation when the code does hit it during execution, you'd have to do the old:
    do { fprintf(stderr, "unreachable\n" } while(0);
trick, which is what I tested in my fork, which due to the macro nature, means you have to sprinkle:
    #include <stdio.h>
all over the place (unless you like the atrocious "include within the macro" method), which isn't great...

**Comment by munificent** [comment]
In release mode, I don't want any errors printed. Like assertions, the `UNREACHABLE()` calls should just disappear so that they don't add overhead to the code. That does, of course, lead to compile errors in a function that doesn't have a `void` return type.

I think the safest bet here is probably just to add explicit `return`s to those functions with dummy values after the `UNREACHABLE()` calls. That's what I originally had before I tried to be clever and use `__builtin_unreachable()`.

**Comment by munificent** [comment]
OK, it should fallback to doing nothing on older versions of GCC, and I added explicit returns in all of the places where that leads to a missing return.

Can you let me know if this works for you? Thanks!

**Comment by ppearson** [comment]
Yep, works fine - thanks!

**Comment by munificent** [comment]
\o/
