### ISSUE TITLE
pull/clone fails on windows: cannot create folder `aux`

### ISSUE THREAD

**Issue by Nelarius** [munificent/wren#309]
The `src/aux` folder is causing `git clone` and `git pull` to fail in windows, because apparently `aux` (and [and a few other names](http://blog.onetechnical.com/2006/11/16/forbidden-file-and-folder-names-on-windows/)) are actually reserved names!

**Comment by severak** [comment]
Maybe this is also the reason why it doesn't compile with mingw32.

**Comment by Nelarius** [comment]
Indeed. After pulling the latest changes, the compiler failed to find `wren_aux_meta.h` and other files, as they are in `src/aux/`, causing a compilation failure.

**Comment by munificent** [comment]
Whoops! I'll come up with a better name for that directory. Sorry!

**Comment by Nelarius** [comment]
Great, thanks! :+1:
