### ISSUE TITLE
(from..to) != (from...to-1)

### ISSUE THREAD

**Issue by horv** [munificent/wren#315]
```
var a = (1..3)
var b = (1..4)

a.toList == b.toList  // == false
a == b                // == false

b = (1..3)
a.toList == b.toList  // == false // Great
a == b                // == true  // Ok, Ranges are values

b = (1...4)
a.toList == b.toList  // == false // Great
a == b                // == false // What??
```

**Comment by bjorn** [comment]
I think it's because `..` creates a different type of range than `...`. The latter is not inclusive, and the range object remembers this rather than simply subtracting 1 from the last value.

**Comment by minirop** [comment]
ranges are compared field by field: https://github.com/munificent/wren/blob/master/src/vm/wren_value.c#L1180

**Comment by horv** [comment]
Of course, bjorn, that explain _why_ but, without a key justification, this behavior is IMO not convenient nor logical, and more _surprising_ than
```
(from..to) == (from...to-1)
```

minirop, how that explain the mentioned issue?

Thanks!

**Comment by minirop** [comment]
@horv, because (1..3) is equals to:
```
var from = 1
var to = 3
var isInclusive = true
```
while (1...4) is equals to
```
var from = 1
var to = 4
var isInclusive = false
```
a.from == b.from, but a.to != b.to and a.isInclusive != b.isInclusive. To make what you expect work, the code could be changed to something like:
```
aRange->to - (aRange->isInclusive ? 0 : 1) == bRange->to - (bRange->isInclusive ? 0 : 1)
```

**Comment by horv** [comment]
Thanks for your effort, @minirop , but I tell you the same thing I told @bjorn : does not seem worthwhile. We have the ```isInclusive``` method _and_
```
aRange->to - (aRange->isInclusive ? 0 : 1) == bRange->to - (bRange->isInclusive ? 0 : 1)
```
instead
```
a == b
```
(not a completely fair comparison, but ...)

**Comment by horv** [comment]
Summarizing: ```...``` is nice and good syntactic sugar for ```..to-1```, but I think if
```
var a = (1..3)
var b = (1..3)
a == b // true
```
then
```
var a = (1..3)
var b = (1...4)
a == b // true
```
should also be.

**Comment by minirop** [comment]
```
aRange->to - (aRange->isInclusive ? 0 : 1) == bRange->to - (bRange->isInclusive ? 0 : 1)
```
is not to replace `a == b`, but a patch that could be proposed for the VM to make `(1..3) == (1...4)` return `true`. (see my first message)

**Comment by munificent** [comment]
This is a weird corner of ranges. The behavior is deliberate, but subtle and I'm not sure if it's ultimately that useful. The things to keep in mind are:

1. Ranges aren't limited to just integers.
2. They are a general-purpose data structure, like numbers, and not only for use for iterators.

So, for example, I might potentially want to use a range for something interval arithmetic. Or maybe I want a function that produces all the numbers inside a range, counting by 0.1:

```
decimals(range) {
  var result = []
  var i = range.start
  while (i <= range.end) {
    if (i == range.end && !range.isInclusive) break
    result.add(i)
    i = i + 0.1
  }
}
```

So `...` really isn't `..to-1`, it's more like `..to-epsilon`. But it's clearer just to realize that `isInclusive` is a fundamental bit of data in the range and is part of its value.
