### ISSUE TITLE
How should method collisions be handled?

### ISSUE THREAD

**Issue by munificent** [munificent/wren#317]
Right now, Wren lets you define the same method twice in the same class:

```
class Foo {
  foo() {}
  foo() {}
}
```

There's no error here and the last one wins. This seems less than optimal. :(

Detecting this case is kind of a pain, but I think we want to do it before we get stuck with *having* to allow duplicate definitions. We'll probably just need a buffer or map of signature strings in ClassCompiler for the methods that have been defined so far, and check in there for before a method is defined.

**Comment by bjorn** [comment]
Raising some kind of redefinition error seems helpful to me.

**Comment by minirop** [comment]
a buffer of int could do it. containing the index of the signature in the methodNames array.

**Comment by munificent** [comment]
> a buffer of int could do it. containing the index of the signature in the methodNames array.

Ah, right. I forgot we keep the signatures around already. Great idea!
