### ISSUE TITLE
Choose to make either static OR shared libwren instead of both.

### ISSUE THREAD

**Issue by ppvk** [munificent/wren#322]
Not a big deal, and this likely is a feature that would only benefit my project in a small way, but having the ability to `make` a static libwren by itself would remove one warning from my emscripten build.

When I run `emmake make vm`, emscripten filters `make` through a bunch of fancy JS building stuff, throwing a warning when it tries to build the linked library. I only use the static one, so the warning doesn't hurt anything, but it's a little annoying.

**Comment by minirop** [comment]
as a workaround, you can try: `make -f util/wren.mk lib/lib$(WREN).a`
(you'll have to adapt $(WREN) yourself based on util/wren.mk#L43 if you choose to change MODE, LANG and ARCH variables)

**Comment by ppvk** [comment]
Awesome! That worked out just fine.

**Comment by munificent** [comment]
@minirop's workaround is a good one, but this seems like an entirely reasonable thing to do, so I added new build targets, `make shared` and `make static`.

**Comment by ppvk** [comment]
Thanks a bunch!
