### ISSUE TITLE
Embedding API request: `config.errorFn`

### ISSUE THREAD

**Issue by ppvk** [munificent/wren#332]
Embedders currently can set the `writeFn` for their VMs using a `WrenConfiguration` object.
I would like a similar process for wren runtime error output.

My particular use case is an in-browser wren editor with on-screen debugging, but I expect this feature could be useful for other types of applications.

I have a solution on my end that involves configuring emscripten, but this seems useful enough to merit a pull request.

I'm not really competent in C, but I think this could be achieved by having all the `printf`s [here](https://github.com/munificent/wren/blob/b7ed774da306460120eff9b5e3d9eeec9342c962/src/vm/wren_debug.c) store to some string buffer, passing that to a `config.errorFn`.

I'll start there, and see where that takes me.

**Comment by munificent** [comment]
Yes, allowing the embedder to control all error output is definitely on my TODO list. I haven't yet because, as you note, you have to do some sort of string buffering to handle formatting and printf.

**Comment by ppvk** [comment]
Wow, didn't notice that #265 was pretty much identical to this bug. I'll close and continue working on this over there.
