### ISSUE TITLE
Addition of a build system generator

### ISSUE THREAD

**Issue by elfring** [munificent/wren#334]
I suggest to reuse a higher level build system than [your current make file](https://github.com/munificent/wren/blob/bec5181bdbc63c91447995135d322df23b510c0f/Makefile#L1 "Update candidate") so that powerful checks for software features will become easier.
* [CMake](http://cmake.org/ "CMake build system")
* [Autotools](http://www.gnu.org/software/autoconf/#TOCintroduction "GNU build system")

**Comment by IsaacWoods** [comment]
I don't any authority here, but I'll throw my two cents in: why? I use plain Make for all my projects and it seems to work very well for Wren. I know that it seems a little intimidating to people who aren't familiar with their syntax, but they're very powerful on their own.

**Comment by elfring** [comment]
* Does [a tool like "autoscan"](https://www.gnu.org/savannah-checkouts/gnu/autoconf/manual/autoconf-2.69/html_node/autoscan-Invocation.html "Using autoscan to create configure.ac") show any software dependencies that you find worth for further considerations?
* How do you think about to support more development environments by [the reuse of build system generators](http://www.cmake.org/cmake/help/v3.3/manual/cmake-generators.7.html#cmake-generators "Selection for build tool generators")?

**Comment by IsaacWoods** [comment]
Makefiles can be used on *NIX and OSX using the native toolchains, and [this](http://gnuwin32.sourceforge.net/packages/make.htm) can be used on Windows (or make(1) through Cygwin) - I don't think support for different development environments is really needed. But at the end of the day, it's munificent's call.

**Comment by munificent** [comment]
I could see switching to CMake at some point for the CLI, but Wren's philosophy is about keeping things simple when possible. So far, Make has been OK for our needs. I definitely don't enjoy futzing with build files and configuration systems, so the less I have to do that, the happier I am, and the more I can get done on Wren itself in my limited time.

**Comment by paulsapps** [comment]
Using CMake makes building on Windows much easier.. it would be a lot easier than manually maintaining the current visual studio projects no?

**Comment by munificent** [comment]
> it would be a lot easier than manually maintaining the current visual studio projects no?

Yeah, maybe. Wren doesn't have many dependencies or source files, so my impression is that keeping the VS solution in sync isn't too much effort.

**Comment by kirbyfan64** [comment]
@munificent Have you ever heard of [Bakefile](http://bakefile.org)? The basic idea behind it is that you can generate Makefiles and VS project files, and they *can be checked into version control*. So no-one needs to download anything separate. It's not like CMake, where even renaming the directories can screw you.

**Comment by paulsapps** [comment]
Sounds exactly like premake to me, CMake won't screw you if you rename a directory - it will fail to generate since files under that dir won't be found, same as any other build system.

**Comment by kirbyfan64** [comment]
@paulsapps No; I meant rename the directory everything is in. CMake sometimes uses absolute paths in its generated Makefiles.

**Comment by paulsapps** [comment]
Ah right yeah, CMake usually will, the idea is that you just re-run CMake to re-gen the makefile/sln/xcodeproject/codeblocks/ninja etc.

**Comment by munificent** [comment]
> @munificent Have you ever heard of Bakefile?

I hadn't, thanks.

> The basic idea behind it is that you can generate Makefiles and VS project files, and they can be checked into version control. So no-one needs to download anything separate.

Checking in the generated files is a great idea, though I suppose we could do that with CMake or anything else too. I'm generally leery of Bakefile because my experience is that there are a million younger project-file-generators like that (premake, et. al.) and few of them are very full-featured.

I don't want to run into a case where we need to be able to generate something into the Makefile and the generator doesn't support it and we're stuck.

**Comment by RobLoach** [comment]
I added a CMake project over at https://github.com/wren-lang/wren/pull/997 .... Doesn't replace the build process, just adds on a CMake definition file.
