### ISSUE TITLE
What is `CODE_X`, and where are they defined?

### ISSUE THREAD

**Issue by ppvk** [munificent/wren#339]
Working on the JavaScript implementation and I'm coming across the `CODE_SUPER_0` and friends. They look like something I'd toss in an enum, but I can't seem to find where they get declared. I know there's a 1-1 relationship between them and what's in `wren_opcodes.h`, but I'm at a bit of a loss where the `CODE_` folks are created.

**Comment by krypt-n** [comment]
````C
typedef enum
{
  #define OPCODE(name, _) CODE_##name,
  #include "wren_opcodes.h"
  #undef OPCODE
} Code;
```

This is in wren_vm.h lines 13-18.

wren_opcodes.h gets included with each `OPCODE` entry defined to be a element in this enum.

**Comment by ppvk** [comment]
Awesome! thanks a bunch!
