### ISSUE TITLE
modifications required to build in windows

### ISSUE THREAD

**Issue by RallyTronics** [munificent/wren#342]
The following lines need to be added to the top of io.c:

```
#if defined(WIN32) || defined(WIN64)
#include <sys\stat.h>
#define S_IRUSR _S_IREAD 
#define S_IWUSR _S_IWRITE
#define O_SYNC 0
#define S_ISREG(m) (((m) & S_IFMT) == S_IFREG)
#define S_ISDIR(m) (((m) & S_IFMT) == S_IFDIR)
#endif

```
In addition, process.c needs to be added to the VS project in util

**Comment by munificent** [comment]
I don't have access to a Windows machine or VS. Would you be able to send me a pull request with this and/or the VS project change?

**Comment by RallyTronics** [comment]
Will do!

On Tue, Mar 15, 2016 at 7:51 AM, Bob Nystrom <notifications@github.com>
wrote:

> I don't have access to a Windows machine or VS. Would you be able to send
> me a pull request with this and/or the VS project change?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/munificent/wren/issues/342#issuecomment-196827469
>



-- 
John Lagerquist
Chief Engineer
RallyTronics LLC
801-866-5981

**Comment by munificent** [comment]
This is done now, right?
