### ISSUE TITLE
How to embed into a game loop?

### ISSUE THREAD

**Issue by paulsapps** [munificent/wren#358]
This might seem like a stupid question, but lets say I have a game loop in C++ like so:

```
void Update()
{
   printf("Update\n");
}

void Render()
{
   printf("Render\n");
}

void InitScripts()
{
  // here I can create a wren VM, what is the correct way to "start" the scripts? 
  // I assume load the "main" script from disk and then use wrenInterpret()?
}

void UpdateScripts()
{
  // if InitScripts is correct and the "main" script has created some objects, how do I "tick" them
  // in here? There is no wrenContinueExection() or the likes?
}

void MainLoop()
{
 InitScripts();
 for(;;)
 {
   Update();
   UpdateScripts();
   Render();
 }
}
```

I can't figure out how this should fit together unless I make the script "own" the game loop and call the update/render stuff?

**Comment by IsaacWoods** [comment]
I'd probably have an `Update()` method in the Wren script, and then iterate through the scripts in `UpdateScripts` and invoke the method. I'm not well versed in the API, however, so I can't tell you how to do that.

**Comment by munificent** [comment]
This is a great question, and one I should eventually write some detailed docs on. You have the right basic idea. I would do something like this:

```c
WrenVM* vm;
WrenValue* gameHandle;
WrenValue* updateHandle;

void Update()
{
   printf("Update\n");
}

void Render()
{
   printf("Render\n");
}

void InitScripts()
{
  WrenConfiguration config; 
  wrenInitConfiguration(&config);
  // Other configuration...
  vm = wrenNewVM(&config);

  // Compile and run the top level code.
  wrenInterpret(vm, mainScript);

  // Now grab a handle to the "Game" class and make a handle to call its
  // "update()" static method.
  wrenEnsureSlots(vm, 1);
  gameHandle = wrenGetVariable(vm, "main", "Game", 0);
  updateHandle = wrenMakeCallHandle(vm, "update()");
}

void UpdateScripts()
{
  // Call "Game.update()".
  wrenEnsureSlots(vm, 1);
  wrenSetSlotValue(vm, 0, gameHandle);
  wrenCall(updateHandle);
}

void MainLoop()
{
  InitScripts();
  for(;;)
  {
    Update();
    UpdateScripts();
    Render();
  }

  // Free everything.
  wrenReleaseValue(vm, gameHandle);
  wrenReleaseValue(vm, updateHandle);
  wrenFreeVM(vm);
}
```

You could call `wrenInterpret()` each frame and execute a little chunk of code like "Game.update()" each frame, but that would be super slow. `wrenInterpret()` has to parse and compile the source each time, so it isn't designed to be on the critical path.

Instead, you compile a chunk of code once and leave all of the class definitions and global objects in memory in the VM. Then you grab a handle to those and make call handles for the methods you want to invoke. Then you can use those to very quickly call a method on an object. (In the case of a static method, the object is just the class itself.)

The Wren code for this would look something like:

```scala
class Game {
  static update() {
    // Walk through the list of game objects and update each one,
    // or whatever else you want to do every frame...
  }
}

// Do any other initialization you want here. Create objects, etc.
```

When `update()` returns, the call to `wrenCall()` will return and you can proceed back in your C code.

You will also get control returned back to C if the current fiber yields, so you can use fibers if you want your Wren code to appear to be in charge of the game loop. Something like:

```scala
class Game {
  static update() {
    // Just bounce to the game loop and let it take over.
    // We use transfer() and not call() here because when the
    // game loop yields, we want to go straight back to C,
    // not to here.
    gameLoop.transfer()
  }
}

// Create a game loop in Wren.
var gameLoop = Fiber.new {
  while (true) {
    // Update the entities, etc.

    // Give control back to C.
    Fiber.yield()
  }
}
```

I haven't tested any of this, but that *should* work. If not, let me know.

**Comment by paulsapps** [comment]
I think this has filled in my mental gaps, I'll give it a go thanks!

**Comment by paulsapps** [comment]
Is it correct that wrenGetVariable must be called before each wrenCall?

```
void InitScripts()
{
    WrenConfiguration config;
    wrenInitConfiguration(&config);
    config.bindForeignClassFn = ClassBinder;
    config.bindForeignMethodFn = FunctionBinder;
    config.writeFn = Write;
    config.errorFn = Error;

    // Other configuration...
    vm = wrenNewVM(&config);

    // Compile and run the top level code.
    wrenInterpret
    (vm, 
        "System.print(\"Init\")\n"
        "class Game {\n"
        "   static update() {\n"
        "       System.print(\"Do update\")\n"
        "   }\n"
        "}\n"
    );

    // Now grab a handle to the "Game" class and make a handle to call its
    // "update()" static method.
    wrenEnsureSlots(vm, 1);
    wrenGetVariable(vm, "main", "Game", 0);
    updateHandle = wrenMakeCallHandle(vm, "update()");
}

void UpdateScripts()
{
    // Call "Game.update()".
    wrenEnsureSlots(vm, 1);
    wrenGetVariable(vm, "main", "Game", 0);
    wrenCall(vm, updateHandle);
}

void MainLoop()
{
    InitScripts();
    for (;;)
    {
        Update();
        UpdateScripts();
        Render();
    }

    // Free everything.
    wrenReleaseValue(vm, updateHandle);
    wrenFreeVM(vm);
}
```

**Comment by bjorn** [comment]
> Is it correct that wrenGetVariable must be called before each wrenCall?

I think @munificent meant that you use `wrenGetSlotValue` in addition to `wrenGetVariable` in the initialization, to avoid looking up this variable each time again, since you can then use `wrenSetSlotValue` before the `wrenCall`.

**Comment by paulsapps** [comment]
So the "correct" way is:

```
    wrenEnsureSlots(vm, 1);
    wrenGetVariable(vm, "main", "Game", 0);
    value = wrenGetSlotValue(vm, 0);
    updateHandle = wrenMakeCallHandle(vm, "update()");
}

void UpdateScripts()
{
    // Call "Game.update()".
    wrenSetSlotValue(vm, 0, value);
    wrenCall(vm, updateHandle);
}
```

?

**Comment by bjorn** [comment]
Well, almost I guess. Seems like you forgot `wrenEnsureSlots` in the `UpdateScripts` function. I'm not sure if it's needed to call that each time, but @munificent did so in his code.

**Comment by munificent** [comment]
> I think @munificent meant that you use wrenGetSlotValue in addition to wrenGetVariable in the initialization, to avoid looking up this variable each time again.

Right.

> So the "correct" way is:

Yup! Though, like @bjorn notes, you'll also want to call `wrenEnsureSlots()` in update too.

When you start setting up the stack before a `wrenCall()`, Wren internally keeps track of the fiber it's going to use for that call. When you call things like `wrenSetSlotValue()`, it's that fiber's stack where things are stored.

In Wren, fiber's don't have a fixed-size stack. They grow dynamically as needed. When possible, `wrenCall()` will reuse a previously completed fiber to avoid the overhead of allocating a new one, so you often already do have enough stack space.

But you can't *assume* that, so the safe thing to do is call `wrenEnsureSlots()` each time. In the common case where there is enough stack, it just does a quick check and returns, so there's little overhead.
