### ISSUE TITLE
docs in Firefox: <output> is shifted down by one line

### ISSUE THREAD

**Issue by wojdyr** [munificent/wren#363]
Just to let you know. In Firefox 46.0 on Ubuntu it looks like this:

![screenshot - 190516 - 15 27 17](https://cloud.githubusercontent.com/assets/491873/15397074/ab7a66f6-1dd6-11e6-90be-f1d4dbe2ff6e.png)

**Comment by munificent** [comment]
Fixed by d64af5d6a500529b245bf5dcf997637a8878dff7.
