### ISSUE TITLE
Jit on PC platform?

### ISSUE THREAD

**Issue by paulsapps** [munificent/wren#371]
I know a core idea behind this language is that it should be fast without a Jit since native code gen on Consoles/mobile is forbidden. However on Windows/OSX/Linux it is not forbidden.

Are there any forks which implement a Jit - would a Jit ever be considered?

**Comment by minirop** [comment]
Not to my knowledge. and the language is not mature, so it may be too soon yet for JIT.

**Comment by munificent** [comment]
> would a Jit ever be considered?

I'm certainly not opposed to other implementations of Wren that JIT, but it's probably unlikely that the the implementation I maintain will. I don't have the expertise to write and maintain a JIT.

**Comment by feliwir** [comment]
Notice: I usually use [Asmjit](https://github.com/asmjit/asmjit) when it comes to JIT and I'd gladly try to add that to Wren, but as far as i know Wren should stay C Compliant? Is it maybe possible to add that as optional module?

**Comment by refi64** [comment]
@feliwir If you want something in C, you could try DynAsm...

**Comment by feliwir** [comment]
@refi64 DynAsm requires Lua during the build stage, if this is prefered i can also go that route i guess

**Comment by munificent** [comment]
> I'd gladly try to add that to Wren, but as far as i know Wren should stay C Compliant?

Yes, the core Wren implementation is plain and should be plain C. I also think it should avoid the complexity of a JIT. If you'd like to fork Wren and add it there, that would be totally great. I just want to ensure that this implementation of Wren stays pretty simple and hackable.
