### ISSUE TITLE
Overwritable import semantics

### ISSUE THREAD

**Issue by sauer2** [munificent/wren#378]
Out of curiosity, is it possible to overwrite the default import semantics? For example, the person embedding Wren could want to:

- load from a fixed directory/archive
- load snippets of code from a document in memory
- disable importing on compile time

**Comment by minirop** [comment]
Wren does not know how to import a module. You'll have to tell it with https://github.com/munificent/wren/blob/master/src/include/wren.h#L128

**Comment by sauer2** [comment]
Cool, so it's already built-in, basically.
