### ISSUE TITLE
Squirrel vs wren

### ISSUE THREAD

**Issue by stefanos82** [munificent/wren#386]
First of all @munificent congrats for this elegant language. It looks awesome.

My question is: have you seen Squirrel before? If not, how come? Wren looks so much alike Squirrel in so many ways.

Other than that, keep up the good work mate.

Cheers.

**Comment by minirop** [comment]
The issue tracker may not be the best place to discuss about that. There's [a forum](https://groups.google.com/forum/#!forum/wren-lang) on google groups.

**Comment by stefanos82** [comment]
Very well. Time to close this ticket then and repost it on forum.

**Comment by munificent** [comment]
This is a great question! Yes, I'm familiar with Squirrel. Like @minirop notes, the mailing list is great for this. (Though I admit, I'm way behind on email there. So busy right now.)

**Comment by stefanos82** [comment]
Yes, I know that there is a mailing list which is appropriate for such topics; but it forces you to subscribe first in order to set a simple question which is absurd in my opinion, that's why I have decided to ask it here.
