### ISSUE TITLE
Clarify docs around expression-bodied blocks

### ISSUE THREAD

**Issue by verpeteren** [munificent/wren#390]
Accourding to the documentation: 

```
The body of a function is a block. If it is a single expression—more precisely if there is no newline after the { or parameter list—then the function implicitly returns the value of the expression. 
```

```
Sometimes, though, a statement doesn’t fit on a single line and jamming a newline in the middle would trip it up. To handle that, Wren has a very simple rule: It ignores a newline following any token that can’t end a statement. 
```

While playing around I was a several times rather confused.

I have prepared the following testcase 'test/language/method/returns.wren'

```
class Foo {
  one_noreturn() { true }
  multi_noreturn() {
    true
  }
  multi_return() {
    return true
  }
  one_return() { return false }               //This does not work as I naively expected
}

var one_noreturn = Fn.new { true }
var multi_noreturn = Fn.new {
    true
}
var multi_return = Fn.new {
    return true
}
var one_return = Fn.new { return false }     //This does not work as I naively expected
```

```
FAIL: test/language/method/returns.wren
      Unexpected error:
      [main line 9] Error at 'return': Expected expression.
      Unexpected error:
      [main line 9] Error at 'false': Expect '}' at end of block.
      Unexpected error:
      [main line 19] Error at 'return': Expected expression.
      Unexpected error:
      [main line 19] Error at 'false': Expect '}' at end of block.
      Expected return code 0 and got 65. Stderr:
      [main line 9] Error at 'return': Expected expression.
      [main line 9] Error at 'false': Expect '}' at end of block.
      [main line 19] Error at 'return': Expected expression.
      [main line 19] Error at 'false': Expect '}' at end of block.

```

Did I misinterpret the documentation, or is this a kind of bug?

**Comment by munificent** [comment]
The behavior is deliberate. If you don't have a newline after `{`, then you can only have an expression, not a statement. `return` is a statement.

The docs should definitely be clearer on the statement/expression distinction. :)

As far as this goes:

> Sometimes, though, a statement doesn’t fit on a single line and jamming a newline in the middle would trip it up. To handle that, Wren has a very simple rule: It ignores a newline following any token that can’t end a statement. 

That's referring to something a little different. It's not talking about a newline *before* a statement, it's talking about a newline in the *middle* of one. It's what allows code like this to work:

```
something +
  somethingElse
```

Since `+` can't end a statement, the newline after it is ignored and Wren treats the above two lines like:

```
something + somethingElse
```

**Comment by verpeteren** [comment]
I wondered why that code break depending on it's formatting. Your explanation makes is clear.
