### ISSUE TITLE
Help with Wren?

### ISSUE THREAD

**Issue by minecraftlog21** [munificent/wren#397]
Hello, I'm currently trying to use Wren for a project of mine. And am trying to add a variable increment feature. like "i++" . I who'd love it if you pointed me into the correct direction.

~ Alexander
    Thank you for your time.

**Comment by iwillspeak** [comment]
I think you'd have to add knowledge of the operator to the parser as is done for assignment of [bare names](https://github.com/munificent/wren/blob/master/src/vm/wren_compiler.c#L2117) and [properties](https://github.com/munificent/wren/blob/master/src/vm/wren_compiler.c#L1898). This is different from most operators which are [defined as primitive functions](https://github.com/munificent/wren/blob/master/src/vm/wren_core.c#L1246).

**Comment by minirop** [comment]
Maybe you can also try translating it as a [prefix operator](https://github.com/munificent/wren/blob/master/src/vm/wren_compiler.c#L2572) (so "++i" instead of "i++") or you let it be a simple token then when the parser finds it, it emits "push 1", "call+(_)" as if it found "i+1"

**Comment by iwillspeak** [comment]
It's not the computing of the increment that is the difficult bit. You
could do that with a `(_)++` method. It's storing the result back in the
variable which means that the parser/compiler need to know about it.

**Comment by minecraftlog21** [comment]
Sorry for the noobie question but what exactly fits the 'TOKEN_NAME' token?

**Comment by minecraftlog21** [comment]
I'm going to go through and play with compiler & vm code, until I have a compleat understanding of it then I'll start tweaking it. Instead of diving head first.
