### ISSUE TITLE
Switching to a more permissive licensing, even

### ISSUE THREAD

**Issue by r-lyeh** [munificent/wren#41]
Quoting: `"Wren uses the OSI-approved MIT license. I'm not sure exactly what that means, but I went with the most permissive license I could find"`.

Even if im not a expert in the matter, [ZLIB/LibPNG license](http://opensource.org/licenses/Zlib) or [Boost Software License](http://opensource.org/licenses/BSL-1.0) are one step ahead in terms of permissiveness: attribution is optional in binary distributions; whereas in MIT license is always mandatory.

So if you want to go to the most permissive license you could go the ZLIB/LibPNG route (which is very gamedev popular nowadays), BOOST route (which is far less popular) or even Unlicense/Public Domain (which are controversial "licenses" in many countries around the world, afaik).

Just my two cents : )
Thanks for wren & the blog/book.
Keep up the good work

- r-lyeh

PS: if you want to keep going on the MIT route, you could just add an explicit clause on the MIT license [(as seen here)](https://github.com/iryoku/smaa#copyright-and-license) which would makes the license closer to the zlib or boost contexts. Even if looks like an attractive option, I think this new license would need approval from diverse opensource non-profit organizations (FSF, OSI, Copyfree Initiative, Debian, Fedora, etc) before any integration of Wren or derivatives into their products. But then again, I am no license expert in any way.

**Comment by JacobEdelman** [comment]
If you want a more permissive license you could just put this in the public domain ( a statement to that effect in the license file would be all you would need I think). Keep in mind this would mean there would be _no_ restrictions or rules on what people could do with wren. A for-profit company could add in a few smallish changes (such as additional builtin functions) or something and release their own version commercially.

**Comment by munificent** [comment]
I'm hesitant to change to a different license mainly because I've been using MIT for a while and I'm comfortable with it. I do like the clarification you mention though. I'm fine with shipped executables not including Copyright/attribution. I added that.

Thanks!

**Comment by zeckalpha** [comment]
@JacobEdelman, that's does not apply in all jurisdictions. [CC0](https://creativecommons.org/about/cc0) would be the closest world-wide "public domain" offering. Though I favor MIT; unless there's a documented need for another license, this is just bike-shedding.
