### ISSUE TITLE
fatal: unable to access 'https://chromium.googlesource.com/external/gyp.git/'

### ISSUE THREAD

**Issue by zfjoy520** [munificent/wren#411]
when I install wren on my Mac like docs:
```shell
$ git clone https://github.com/munificent/wren.git
$ cd wren 
$ make 
```

I got following errors:

```shell
Cloning libuv...
Getting tags...
Checking out libuv v1.10.0...
Downloading gyp...
fatal: unable to access 'https://chromium.googlesource.com/external/gyp.git/': Failed to connect to chromium.googlesource.com port 443: Operation timed out

make[1]: *** [deps/libuv/build/gyp/gyp] Error 128
make: *** [release] Error 2
```

I tried again and again, but ..., please help me, tks.

**Comment by bjorn** [comment]
Hmm, it's working fine for me. Does visiting https://chromium.googlesource.com/external/gyp with your browser work?

**Comment by zfjoy520** [comment]
@bjorn 
Yes, in browser, the url: https://chromium.googlesource.com/external/gyp works.

**Comment by iwillspeak** [comment]
Are you on a network which needs a proxy configured, such as a work or school network? It could be that your browser has detected the proxy settings but the command line doesn't know about them.

**Comment by zfjoy520** [comment]
@iwillspeak 
Yes, maybe, I try to download the tgz: https://chromium.googlesource.com/external/gyp.git/+archive/master.tar.gz and place it under the build folder
