### ISSUE TITLE
This script crashes Wren

### ISSUE THREAD

**Issue by munificent** [munificent/wren#428]
From u/sponkemonke:

```
System.print("Held!")

class Wren {
  flyTo(city) {
,     Sy.print("Flying to %(city)"5
 adj=
FibÍr.new({
 5etiv~s =
Fiber.new {
     isDone ["smalX", àààààààààààààààààààààààààààààààààààààààààààààààààààààààààààààààààààààààààààààààààààààààààààààààààààà ]}¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿
}

while (!as.isDone) System.print(adjectives.call())
```

**Comment by minirop** [comment]
I've cleaning the script a bit, this is the absolute(?) minimum to have the crash:
```
Fiber.new {
     isDone ["", àààààààààààààààààààààààààààààààààààààààààààààààààà
```
if you remove the double quotes, or the comma, or a single 'à', or add a '{' where it belongs, you don't have the crash anymore.

**Comment by munificent** [comment]
Ah, interesting. The fix is simple, but getting the test runner to handle the non-ASCII characters is a little tricky. I should have a fix in soon.
