### ISSUE TITLE
A NUL byte in a script will crash Wren

### ISSUE THREAD

**Issue by munificent** [munificent/wren#429]
From u/sponkemonke.

**Comment by minirop** [comment]
maybe ask him a little more data. I only got the crash with my fix attempt of #430.

I did try a script with a NUL byte between 2 statements, the 2nd statement was not executed.
I then put it inside a string, got the "unterminated string" error.
Then inside a method name "fiber.yie[NUL]d()": **Error at end of file: Expect '}' at end of block.**

**Comment by gordonshieh94** [comment]
I was the one who found the crashes using American Fuzzy Lop. I've attached a zip containing a few of the files that cause wren to crash. 
[crashes.zip](https://github.com/munificent/wren/files/863347/crashes.zip)

**Comment by minirop** [comment]
Thanks @gordonshieh94, I manage to find something. The NUL byte is not the error, it shows that wren don't handle unclosed scopes in some cases.

```
{
System
```

gives *** Error in `./wrend': free(): invalid next size (fast): 0x00000000011fbc80 ***

```
{
  System.print("hello")
```

gives *** Error in `./wrend': double free or corruption (out): 0x0000000001190580 ***

The following codes don't crash.
```
// removing the carriage return
// Error at end of file: Expect '}' at end of block.
{ System
```
```
// adding a dot
// Error at end of file: Expect method name after '.'.
{
  System.
```
```
// adding dot and method name
// System metaclass does not implement 'print'.
{
  System.print
```
