### ISSUE TITLE
Show how to create `blondie`

### ISSUE THREAD

**Issue by jcalfee** [munificent/wren#432]
I got lost on block arguments and calling functions:  http://wren.io/functions.html

Can you show how to create the instance called `blondie`?  I can figure it out using http://ppvk.github.io/wren-nest/ so if the docs include this important first step it will be easier.

**Comment by minirop** [comment]
here it is: http://ppvk.github.io/wren-nest/?=32ef95a8f594c18bdb0b0349e8b22108
