### ISSUE TITLE
gyp: Daily bandwidth rate limit exceeded

### ISSUE THREAD

**Issue by minirop** [munificent/wren#437]
the CI can fail because of the daily limit of gyp's repository. [Like it one](https://travis-ci.org/munificent/wren/jobs/216072524).

Is there a mirror without the limit or is copying the repo (or the necessary files of the repo) a thing to do? (so the "[good-known commit](https://github.com/munificent/wren/blob/master/util/libuv.py#L75)" would be "known")

**Comment by paulsapps** [comment]
Why not just add it as a git sub repo? Then its optional for people to clone down with --recursive

**Comment by minirop** [comment]
@paulsapps it would still have the issue since it's Travis' ip that gets "banned" from checking the repo (since the makefile just git clone the repo).

**Comment by bjorn** [comment]
> Oh, dang. It might make sense to vendor libuv into the main Wren repo.

Why put whole of libuv in it if only gyp fails to clone? Maybe just gyp would be small enough to include in the repo, if there really isn't some mirror or package that could be installed instead?

**Comment by munificent** [comment]
> Why put whole of libuv in it if only gyp fails to clone? 

Oh, good point. We could vendor gyp in. I wonder if libuv has or is planning to move off gyp anyway? My understanding is that it's basically dead. I don't think Google uses it for anything anymore. (Chrome now uses GN and Ninja.)

**Comment by kirbyfan64** [comment]
@munificent Doesn't look like it: https://github.com/libuv/libuv/pull/952

**Comment by munificent** [comment]
OK, I took a stab at solving this: https://github.com/munificent/wren/pull/447

It works on my Mac and on Travis, but I'd like to see what people think and hopefully get some Windows and Linux testing before I merge it in. So... thoughts?

**Comment by munificent** [comment]
Alright, libuv and gyp are vendored into the repo now. :)
