### ISSUE TITLE
Strange list behaviour

### ISSUE THREAD

**Issue by ElFeesho** [munificent/wren#439]
The following wren code (on master):

```
var activate = Fn.new {
    var roster = ["boop", "doop"]
    System.print("Roster: %(roster)")
    roster.clear()
}
```

When invoked from C++:

```c++
void wren_macro_runner::activate() {
    wrenEnsureSlots(_wrenVm.get(), 1);
    wrenGetVariable(_wrenVm.get(), "main", "activate", 0);
    wrenCall(_wrenVm.get(), wrenGetSlotHandle(_wrenVm.get(), 0));
}
```

Results in my `writeFn` function being called with `Roster: System` ?!

Also results in the `errorFn` being invoked with the following parameters:
Line: -1
Module: (none)
Message: String does not implement 'clear()'.

And then:

Module: main
Line: 10
Message: new(_) block argument

I can't figure out why this would be the case, I'm sure I'm likely doing something very wrong.

My wren integration can be found [here](https://raw.githubusercontent.com/ElFeesho/tgbdual/master/sdl_ui/src/scripting/wren_macro_runner.cpp)

**Comment by munificent** [comment]
I think you're running into the same confusion as is discussed on #444. To call a function from C, you need to invoke its `call()` method.
