### ISSUE TITLE
Bad Performance of System.print()

### ISSUE THREAD

**Issue by questionpython** [munificent/wren#445]
wren
------
```
for (i in 1..999999) {
	System.print(i)
}
real	0m3.306s
user	0m1.060s
sys	0m1.772s
```

--------

lua5.3.1
-----------
```
for i=1,999999 do
	print(i)

real	0m2.858s
user	0m0.776s
sys	0m1.284s
```

----------

php7.1.3
----------
```
<?php
for($i=0; $i<=999999; $i++)
{
	print($i . "\n");    
}
?>
real	0m2.148s
user	0m0.252s
sys	0m1.136s

```

why Performance of wren is bad?

**Comment by kirbyfan64** [comment]
FWIW, benchmarking using a printing loop often isn't the best way to benchmark things, since you end up basically benchmarking the language's printing speed, which isn't a good representation of how fast things really are.

**Comment by questionpython** [comment]
Yes that's right.
But it could be better.
Is it possible that Performance better?

**Comment by munificent** [comment]
Yes, in this case, almost all of the time is being spent on the printing. The looping itself should be quite fast (there is a benchmark for loops for Wren).

It doesn't look like the performance is that different, but there may be some simple things we could do to make it faster. In general, `System.print()` is intended more as a basic debugging aid than it is a high performance IO routine, so performance of it hasn't been considered critical.

**Comment by questionpython** [comment]
So you can make this faster and better of now?
if you can, when can?

tank you :+1:

**Comment by questionpython** [comment]
?

**Comment by munificent** [comment]
The main problem was that Wren was flushing on every System.write(). That's convenient, but unnecessarily slow. I removed that and the performance is around the same as the other languages now.
