### ISSUE TITLE
Additional Capabilities Grammer!

### ISSUE THREAD

**Issue by questionpython** [munificent/wren#450]
::1 
-------
_ Error at newline: Expect '{' after class declaration. _
```
class Wren
{

}
class Wren{

}
class Wren

           {

}
```

::2 
---------
_ Error: Invalid character ';'. _
```
System.print("Hello, world!")
System.print("Hello, world!");
```

**Comment by benpop** [comment]
I believe these are working as intended, per [this thread](https://github.com/munificent/wren/issues/307) and [the creator's response](https://github.com/munificent/wren/issues/307#issuecomment-146316152).

**Comment by munificent** [comment]
@bepop is right. This is working as intended (though I know the looks turns some people off).
