### ISSUE TITLE
Some bugs in the VM source code

### ISSUE THREAD

**Issue by chqrlie** [munificent/wren#457]
Hi Robert!

Congratulations on a very nifty project! Quite refreshing to see concise and elegant code nowadays.

Here are some bugs I found browsing through the code:

* The macro `ALLOCATE_FLEX` in `wren_common.h` is not properly parenthesized:

        define ALLOCATE_FLEX(vm, mainType, arrayType, count) \
            ((mainType*)wrenReallocate(vm, NULL, 0, \
            sizeof(mainType) + sizeof(arrayType) * count))

  This instance would have been problematic if the array type has been different from `char`:

        wren_value.c:670:  ObjString* string = ALLOCATE_FLEX(vm, ObjString, char, length + 1);

**Comment by minirop** [comment]
`ALLOCATE_ARRAY` is missing the same parenthesis around `count` too.

**Comment by bjorn** [comment]
The missing parenthesis around `count` is exactly what @chqrlie was talking about. :-)

**Comment by minirop** [comment]
@bjorn he wrote about `ALLOCATE_FLEX` and I saying that `ALLOCATE_ARRAY` has the same bug.

**Comment by bjorn** [comment]
@minirop Whoops, my bad. :-)

**Comment by munificent** [comment]
Nice catch!
