### ISSUE TITLE
Stack reallocation issue

### ISSUE THREAD

**Issue by chqrlie** [munificent/wren#458]
Hi Robert,

There is a problem in `wrenEnsureStack` in file `wren_value.c`: you adjust the pointers into the reallocated stack by adding an offset to them computed as this:

       long offset = fiber->stack - oldStack;

This is incorrect for at least 2 reasons:

* the difference of 2 pointers, of type `ptrdiff_t` might not fit in type `long`.  Indeed it does not on Windows 64-bit as pointers are 64-bit wide and type `long` only has 32 bits for ugly compatibility reasons.

* the difference of 2 pointers not pointing to the same array is explicitly described in the C Standard as having undefined behavior.  Indeed, even on architectures with a flat addressing space, the 2 pointers might be at a distance that is not a multiple of the size of the type pointed to.  The difference will be computed as the byte offset divided by the size of the object (type in this case `Value`) and whenever this `offset` is added to a pointer, the actual adjustment might be incorrect if the division had a remainder.  In the current implementation, with NAN tagging, the size of type Value is the same as his alignment value, so it is not a problem, but without NAN tagging, the size is twice the alignment value: definitely a problem...

I suggest you change the code to this:

    if (vm->apiStack >= oldStack && vm->apiStack <= fiber->stackTop)
    {
      vm->apiStack = vm->stack + (vm->apiStack - oldStack);
    }

And correct the other fix-ups in this function.  There is a good chance the compiler will generate efficient code for this anyway.

**Comment by munificent** [comment]
Thanks for noticing this!
