### ISSUE TITLE
Figuring out which script causes a runtime error.

### ISSUE THREAD

**Issue by calviken** [munificent/wren#463]
Whenever a runtime error occurs in a script loaded with `wrenInterpret`, the stack trace usually looks something like this:
`<some error>`
`[main line 8] in (script)`

This isn't particularly useful for figuring out which script the error came from, since `wrenInterpret` loads everything into the `main` module.

I noticed there's a function in `wren_vm.h` called `wrenInterpretInModule` that seems like it would solve this problem. (in fact, `wrenInterpret` uses this function directly)

So I have two questions:
1. Is there any reason why `wrenInterpretInModule` isn't declared in `wren.h`?
2. Would this function be a good way to assign a name to a script, or would it have some nasty side-effects? (aside from isolating the contents of the script)

**Comment by JonesAndrew** [comment]
I haven't tried using `wrenInterpretInModule` directly, but if you make a handle with `wrenMakeCallHandle` and then call that through `wrenCall` the stack trace will give you the correct file name.

**Comment by calviken** [comment]
How could Wren know which file the script came from? Or are you talking about modules?

**Comment by JonesAndrew** [comment]
Yep, if you setup your scripts with modules then Wren will know about each files. The way I usually setup my scripts is have one init script which imports all the other scripts, and then I make handles to everything I need and call those instead of using `wrenInterpret` again.

**Comment by calviken** [comment]
I thought about doing it that way. It just seems a bit hacky, and it also interferes with how (I think) the module system should normally be used, i.e. as a way of accessing common code from multiple scripts.

I'm not sure if `wrenInterpretInModule` is the best solution either, but at least you wouldn't have to worry about changing your module loading function to accommodate it.

**Comment by calviken** [comment]
did not mean to close this, dang it

**Comment by munificent** [comment]
> This isn't particularly useful for figuring out which script the error came from, since `wrenInterpret` loads everything into the main module.

I'm a little unsure what you mean by "this script". If you pass a string to `wrenInterpret` and it causes a runtime error (that wasn't generated in some other file that string of code imported), then the error is in that string itself, isn't it?

**Comment by calviken** [comment]
>  If you pass a string to `wrenInterpret` and it causes a runtime error (that wasn't generated in some other file that string of code imported), then the error is in that string itself, isn't it?

Sure, but the error callback doesn't know that. It's only given the module name.

**Comment by munificent** [comment]
I'm sorry, I'm still not following. My understanding is:

1. You call `wrenInterpret()` with a string of code.
2. Something in there generates a runtime error.
3. The VM calls your error callback with a module named "main".

At that point, when you see "main", you know that the error is in the string of code you passed it, right? Is it just that you want more control over the name "main"?

**Comment by calviken** [comment]
> Is it just that you want more control over the name "main"?

That's exactly right, and I'm wondering whether `wrenInterpretInModule` is the right way to do it.

**Comment by munificent** [comment]
OK, I get it now. Yes, exposing that (with perhaps a better name) might be a good way to go about it. The fact that "main" is hardcoded in the interpreter is kind of an arbitrary (though convenient for the user) hack.

**Comment by munificent** [comment]
With the new relative import stuff, `wrenInterpret()` now takes a module name in addition to the source, so I think this is done.
