### ISSUE TITLE
When will Embedding API page be complete?

### ISSUE THREAD

**Issue by kornerr** [munificent/wren#465]
Hi.
The whole point of Wren is to be embedded, and there are no examples on how to call C from Wren and Wren from C (i.e. callbacks) at all.
When will it finally happen?

**Comment by minirop** [comment]
see #402

**Comment by kornerr** [comment]
Damn. The blog post which should cover some basics is unavailable!

**Comment by Nelarius** [comment]
Oops, I migrated my stuff over to a new site. Here's the new link: http://nelari.us/post/wren-embedding-1/

**Comment by kornerr** [comment]
Too bad, it was too late for us: http://opengamestudio.org/lang/en/news/2506

However, if anybody provides a way to inherit a C++ base class inside Wren and then override its methods, I'd be glad to verify it works (and add Wren to the list of supported scripting languages of OGS tools).

**Comment by minirop** [comment]
@kornerr I've tried and it's not possible to inherit a foreign class (name of a class implemented in C) that would allow overloading in Wren.

**Comment by Nelarius** [comment]
@kornerr sorry to hear! Either way, lua + sol2 seems like a very solid choice. I got library envy when I saw how good sol2 was 🙂

**Comment by paulsapps** [comment]
Its a shame no one has created a "script VM" that has compilation/static typing or a JIT. Then projects like this would just be a syntax front end to it. Although I guess that radically changes the ideals and goals of wren.

**Comment by Nelarius** [comment]
Sounds like the [NekoVM](http://nekovm.org/) fits the bill, actually. One front-end is the Neko programming language, a dynamic scripting language, but it's also a compilation target for the Haxe programming language which is statically typed. According to [these](https://github.com/r-lyeh/scriptorium) benchmarks, the NekoVM is also fairly performant. Furthermore, Haxe can be compiled to C++.

**Comment by kornerr** [comment]
Using Haxe with additional compilation step is just too much. Furthermore,
it's not really cross-platform. So plain C++ is actually a lot easier. I
tried Haxe :)
Still, thanks for a suggestion.

**Comment by munificent** [comment]
Sorry for the long delay! (It turns out it's really hard to muster the energy to write *more* docs while I'm in the middle of writing an increasingly long book. Who would have guessed?)

A first pass at a complete set of embedding docs are up now: http://wren.io/embedding/

I'd still like to write some more about how to interact with fibers through the embedding API in interesting ways, but that can come later. This should cover all of the main stuff. Thank you for pushing on this so I didn't forget. :)
