### ISSUE TITLE
confusingly similar naming nit: Compiler versus ClassCompiler

### ISSUE THREAD

**Issue by skybrian** [munificent/wren#469]
In `wren_compiler.c`, `getEnclosingClassCompiler` returns a `Compiler`, not a `ClassCompiler`.  To get the `ClassCompiler`, you need to call `getEnclosingClass`. The name clash makes the code rather tricky to read.

I'm wondering if `ClassCompiler` should be renamed to `MethodScope` or `MethodContext` instead? It doesn't seem to be a compiler.

**Comment by minirop** [comment]
The ambiguity is that `getEnclosingClass` is `get - EnclosingClass - Compiler` and not `get - Enclosing - ClassCompiler`. But yeah, maybe `ClassCompiler` should be renamed (like `ClassContext`?)

**Comment by munificent** [comment]
Yeah, I never liked those names. Changed it to "ClassInfo". "Info" is kind of meaningless, but I think it's at least a little better.
