### ISSUE TITLE
Code sample on website / README doesn't actually compile?

### ISSUE THREAD

**Issue by pwoolcoc** [munificent/wren#47]
The code sample at the top of the README doesn't actually compile, should it? Seems like it would need to be changed to this:

```dart
IO.print("Hello, world!")

class Wren {
  adjectives { ["small", "clean", "fast"] }
  languageType { "scripting" }
}
```

**Comment by munificent** [comment]
Eek, you're right! That's what I get for writing that sample before I implemented most of the language!
