### ISSUE TITLE
Unfair Benchmarks

### ISSUE THREAD

**Issue by nikolay** [munificent/wren#473]
Don't compare against LuaJIT if you're going to turn the compiler off!

**Comment by underscorediscovery** [comment]
Stated plainly on the performance page:

> LuaJIT is run with the JIT disabled (i.e. in bytecode interpreter mode) since I want to support platforms where JIT-compilation is disallowed. LuaJIT with the JIT enabled is much faster than all of the other languages benchmarked, including Wren, because Mike Pall is a robot from the future.

**Comment by nikolay** [comment]
You should not compare to it at all or only list the platforms it supports. It's like comparing a fully-equipped Corolla to a Ferrari without the tires. Nobody uses LuaJIT without the JIT! Also, dare to add pypy.
