### ISSUE TITLE
vm.h

### ISSUE THREAD

**Issue by devsnek** [munificent/wren#485]
a few modules reference `vm.h`, and i can't find that anywhere in the source. is it supposed to be `wren_vm.h`?

**Comment by underscorediscovery** [comment]
there's only a `wren_vm.h` that I'm aware of. Can you link to where you see a reference to vm.h?

**Comment by devsnek** [comment]
https://github.com/munificent/wren/blob/c4d08bcb81045f471ff182d48f0a3de353fc0f46/src/module/scheduler.c#L8
https://github.com/munificent/wren/blob/c4d08bcb81045f471ff182d48f0a3de353fc0f46/src/module/timer.c#L7
https://github.com/munificent/wren/blob/c4d08bcb81045f471ff182d48f0a3de353fc0f46/src/module/io.c#L7

changing these to `wren_vm.h` allowed me to build and run wren

**Comment by underscorediscovery** [comment]
Ah it's in the cli module, this is referencing [cli/vm.h](https://github.com/munificent/wren/tree/master/src/cli)

**Comment by devsnek** [comment]
oh ok
