### ISSUE TITLE
Can not use libuv function after built with VS2015?

### ISSUE THREAD

**Issue by shawnye** [munificent/wren#488]
I build wren with VS2015 (nearly successful ,for I built libuv mannally)
wren.exe size 205KB, it seams  not contain functions in libuv
I put libuv.dll under the same directory.

Then I try this wren script file:
`Directory.exists("c:\\")`

error occurred:
<pre>
[main line 1] Error at 'Directory': Variable is used but not defined.
</pre>

Am I missing anything ?

thank you!

**Comment by underscorediscovery** [comment]
can you paste the whole example script? Like do you have the `import` statement that imports Directory ?

**Comment by shawnye** [comment]
The script just one line:
`Directory.exists("c:\\")`

copy from `http://wren.io/modules/io/directory.html`

**Comment by underscorediscovery** [comment]
You will probably want to import the variable. [This page has some docs.](http://wren.io/modularity.html)

The variable is inside the `io` module, so you want to do:

`import "io" for Directory"`

before you use the variable.
Hope that helps!

**Comment by shawnye** [comment]
Yes, that's work, Thanks.
I am not familiar with the syntax , but will soon...
