### ISSUE TITLE
Global variables not accessible from class methods. Is this intended?

### ISSUE THREAD

**Issue by heretique** [munificent/wren#495]
Hi,
i'm playing with Wren and I'm a bit confused about global variables visibility/access and I'm not sure if the actual behavior is intended and if so why?

What I've noticed is that global variables are accessible from module importer and functions/closures/fibers but not accessible from class methods. Take the following code for example:
```
var words = ["small", "clean", "fast"]

class Wren {
    construct new() {}
  flyTo(city) {
    System.print("Flying to %(city)")
  }
  showWords() {
    words.each {|word| System.print(word)}  
  }
}

var func = Fn.new {
    words.each {|word| System.print(word)}
}

var adjectives = Fiber.new {
  words.each {|word| Fiber.yield(word) }
}

while (!adjectives.isDone) System.print(adjectives.call())
var wren = Wren.new() 
wren.flyTo("Paris")
func.call()
wren.showWords()
```

The code works for the function call and for the fiber but not for the class method.
I get this error: "Wren does not implement 'words'. | (null):-1
showWords() | main:11
(script) | main:22" where it seems that Wren is considering "words" as a getter and it is not implemented. Is there a way to access global variables from within a class method (static or not)?
If not, why in some contexts is available but in some not, isn't this non-consistent behavior?

**Comment by underscorediscovery** [comment]
This relates to the upper vs lowercase distinction of the look up rules.

There are other discussions (I can't find the link off hand) but essentially, make it start with an uppercase and it will be visible from the whole module.

**Comment by minirop** [comment]
here it is: http://wren.io/classes.html#implicit-this

**Comment by heretique** [comment]
2. "Else, if the name starts with a lowercase letter, treat it like a method on this."
well I read this section before and somehow I've missed this. Thanks for pointing this out. I've also tested it out and it works as intended.
I guess I can close the issue...
