### ISSUE TITLE
Question: Static type checking and "inner"

### ISSUE THREAD

**Issue by sauer2** [munificent/wren#497]
The FAQ doesn't seem to explain the considerations behind not adding static type checking and the inner keyword from BETA that is mentioned on stuffwithstuff and in Crafting Interpreters.

@munificent Usually, I'd default to "too complicated with not enough to gain for legit-sized scripts" and "too unusual", but since you've got a blog pondering about language features in detail where things often are more fine grained than that, I though, I'd give it a shot and ask if there are more detailed reasons.

Thanks in advance and a happy new year!
Sauer2

**Comment by munificent** [comment]
As far as static types goes, adding a type checker adds a *mountain* of complexity to the language. I do like static types, especially when working on large codebases, but for a little scripting language, I think they are overkill.

As far as inner goes, I am actually pondering it for Wren and have been for years. I haven't found the time to sit down and figure out how to implement it efficiently and see if it makes sense, but it's on my mental list of features to consider before calling Wren 1.0.

**Comment by sauer2** [comment]
Thanks!
