### ISSUE TITLE
how to save the wren object to the file?

### ISSUE THREAD

**Issue by zhang189** [munificent/wren#505]
Do use the foreign class to realize?

**Comment by minirop** [comment]
can you explain what do you mean by "save wren ofject to the file"?

a foreign class is a class that is implemented in C instead of in wren directly.

**Comment by underscorediscovery** [comment]
There is no serialization built in for wren classes - if that's what you meant.
If you want to serialize a wren object to file it would be done manually, either by a foreign or a convention (i.e making and calling a `serialize` function on the objects).

**Comment by zhang189** [comment]
yes, i want to serialization for wren classes to used multiple times . Is there other way could storage  wren object or object data to C application?

**Comment by munificent** [comment]
I'm going to go ahead and close this because I don't have any current plans to add generic object serialization to Wren. I think this is probably something better solved at the user level.
