### ISSUE TITLE
Importing issue

### ISSUE THREAD

**Issue by jclc** [munificent/wren#511]
I've got a weird importing issue where I can't import a module if I'm importing a module that is imported by another module that that module is also importing. I get the error:
```
[RUNTIME] 0.20       Start metaclass does not implement 'vec3'.
  [TRACE]            start@9: start()
  [TRACE]            core@11: init()
```
This is what `start.wren` looks like
```
// Entrypoint for game behaviour

import "test_entity" for Circler, Loiterer
import "trig" for vec3
import "game" for Game

class Start {
	static start() {
		var e1 = Game.addEntity(Circler.new(vec3.new(0.0, 0.0, -6.0)))
		var e2 = Game.addEntity(Loiterer.new())
		e2.move(vec3.new(-20, -2, -3))
	}
}
```
vec3 is also imported in the `test_entity` module and the `entity` module which it imports. `trig` doesn't import anything and vec3's definition is pretty self-explanatory.

**Comment by jclc** [comment]
Don't know if it's related, but earlier I had a similar issue that I fixed by changing the order of imports.

**Comment by underscorediscovery** [comment]
This is likely related to resolution of variables by capitalization - see http://wren.io/classes.html#implicit-this under "Which scope wins?" , vec3 being lower case is likely to cause this type of resolution ambiguity

**Comment by jclc** [comment]
That was it, renaming vec3 to Vec3 fixed it. Thanks a lot.
