### ISSUE TITLE
Grammar error

### ISSUE THREAD

**Issue by mhermier** [munificent/wren#528]
Hi,
Just found an error in the compiler:
```
42:5
```
evaluate to 42 instead of returning and error
Unless I miss-understood something , it should be an error, and forced me to use `parsePrecedence` instead of `expression` [here](https://github.com/munificent/wren/pull/527/commits/d8ca107589b3d68813f4899f8e53875d1ca0b48d#diff-63e9f6605c668349e0d3d6794de6ee22R3386).

**Comment by munificent** [comment]
I can only repro this on the REPL. Is that where you're seeing it? If so, I fixed it there. Elsewhere, the compiler should already handle reporting an error.

**Comment by mhermier** [comment]
I originaly saw it when trying to produce the optional type grammar change.
I thought I needed to artificially increase the required parseExpression
priority for some reasons. But today reading the change again and looking
at priorities, what I made looks it was what was required.

Anyway, with we can hit your change and produce a cryptic error with 'var
foo: 42' returning 'Expected end of file'.
