### ISSUE TITLE
Storing Functions in Classes

### ISSUE THREAD

**Issue by emekoi** [munificent/wren#536]
Is it currently possible to store an instance of Fn as a field inside a class? For example the following code snippet fails to run:
```
class Animal {
    construct new(fn) {
        _greet = fn
    }
    
    greet() {
        _greet()
    }
}

var cat = Animal.new {
    System.print("meow")
}

cat.greet()
```
and gives the error:
```
Error at '(': Expect newline after statement. | main:7
Error at ')': Expected expression. | main:7
```

**Comment by underscorediscovery** [comment]
Hi! the syntax for Fn is `_greet.call()`. [There's some docs about it here](http://wren.io/functions.html#calling-functions), and how classes can respond as functions too if they implement call as well.

**Comment by emekoi** [comment]
Yeah, I just remembered as I was going to bed, but I forgot to close this issue. Thanks, anyway!
