### ISSUE TITLE
Range docs incorrectly use .min in most examples

### ISSUE THREAD

**Issue by vktec** [munificent/wren#540]
The [docs](http://wren.io/modules/core/range.html) for the `Range` class use `.min` rather than `.from`, `.to` and `.max` in the examples for those 3 methods.

**Comment by bjorn** [comment]
Already fixed a long time ago (see #475), but the site needs updating (still hoping #521 will eventually get merged).

**Comment by vktec** [comment]
Ah, okay. Thanks for letting me know
