### ISSUE TITLE
List returned from foreign method isn't always constructed correctly

### ISSUE THREAD

**Issue by azufluup** [munificent/wren#543]
I've got a function in C in which I create a list to be returned to Wren. If the number of list elements exceeds a small number (7 or so), the variable the list isn't 'complete'. The weirdness is that after calling some more Wren code, the returned variable actually gets corrected to a list, and has all of the elements it is supposed to contain.

```wren
var list = Foreign.getList()
// System.write()
for(x in list) {
	System.print(x)
}
```

Without the System.write() following the list declaration, we get ``Error in '(null):-1: Foreign metaclass does not implement 'iterate(_)'.``. When we include the commented line, the list prints normally.

Here's a complete example of how I'm registering the foreign function and verifying we definitely have the slots available:

```c
#include <stdio.h>
#include "wren.h"

static void wren_write(WrenVM *vm, const char *str)
{
	printf("%s", str);
}

static void wren_error(WrenVM *vm, WrenErrorType type, const char *module,
		int line, const char *message)
{
	printf("Error in '%s:%d: %s\n", module, line, message);
}

static void wren_fn_getList(WrenVM *vm)
{
	int num_slots = 100;
	int slot = 0;

	printf("getList default slots: %d\n", wrenGetSlotCount(vm));
	wrenEnsureSlots(vm, num_slots);
	printf("getList ensured slots: %d\n", wrenGetSlotCount(vm));

	wrenSetSlotNewList(vm, slot);

	while(++slot < num_slots) {
		wrenSetSlotDouble(vm, slot, (double)slot);
		wrenInsertInList(vm, 0, -1, slot);
	}
}

static WrenForeignMethodFn wren_bind_foreign_methods(WrenVM *vm, const char *module,
		const char *class_name, bool is_static, const char *signature)
{
	return wren_fn_getList;
}

int main(void)
{
	WrenVM *vm;
	WrenConfiguration config;

	wrenInitConfiguration(&config);
	config.writeFn = wren_write;
	config.errorFn = wren_error;
	config.bindForeignMethodFn = wren_bind_foreign_methods;

	vm = wrenNewVM(&config);

	wrenInterpret(vm,
			"class Foreign {\n"
			"	foreign static getList()\n"
			"}\n"
			"\n"
			"var list = Foreign.getList()\n"
			//"System.write(\"\")\n"
			"for(x in list) {\n"
			"	System.print(x)\n"
			"}\n"
		);

	wrenFreeVM(vm);
	return 0;
}
```
I don't know if the workaround is limited to printing. Last night I thought declaring ``var i = {}`` made the list right again, but I can't reproduce that now. Unhooking or emptying config.writeFn still leaves it 'working' though. I tried to poke around the internals and see what was happening when a function is called but got a bit lost :)

This isn't limited to lists. I separately fiddled with a pending pull request for creating maps in slots (https://github.com/munificent/wren/pull/421) and it acts the same.

**Comment by mhermier** [comment]
You hit the re-entrancy issue, that has yet too be fixed. Calling `wrenEnsureSlots` from a foreign can corrupt the stack, since it doesn't affect `api_stack`.

**Comment by azufluup** [comment]
Duplicate of #510
