### ISSUE TITLE
[Question] How could one handle shared_ptr(s) to foreign objects seamlessly? 

### ISSUE THREAD

**Issue by heretique** [munificent/wren#544]
Suppose I have a foreign class like this in C++:
```C++
class Foreign {
public:
    Foreign(std::shared_ptr<Foreign> parent);
    ~Foreign();
    foo();
    std::shared_ptr<Foreign> getParent();
private:
    std::shared_ptr<Foreign> _parent;
}
```
and I expose this to Wren as 
```
foreign class ForeignWren {
    foreign new(parent)
    foreign foo()
    foreign getParent()
}
```
 and also bind ```std::shared_ptr<Foreign>``` as 
```
foreign class ForeignWrenPtr {
    foreign get()
}
```
Is it possible to overload somehow the method call operator "." on ForeignWrenPtr to be able to call methods on ForeignWren as if ForeignWrenPtr would be a raw pointer to Foreign class? What I want is to be able to transparently treat shared pointers to foreign classes as raw pointers when calling methods but keep passing them by value in order to retain reference counting.

Right now I expose the ```std::shared_ptr::get()``` method. My code in Wren looks like this right now:
```
var parent = foreignObject.getparent()
parent.get().foo()
```
but it would be great if I could get rid of the intermediary "get" method and overload the method call operator "." in a similar fashion as in C++ ```std::shared_ptr<T>``` overloads the class member access operator "->" to use the code like this:
```
var parent = foreignObject.getparent()
parent.foo()
```

[Note] I use @Nelarius 's [Wren++](https://github.com/Nelarius/wrenpp) library for binding.

**Comment by minirop** [comment]
simple: no.

Do you really need to have `shared_ptr` in your public API? Couldn't `getParent` simply return `Foreign*`?

**Comment by heretique** [comment]
Yes and no, I mean I could get around that and expose raw pointers but that would require redesigning the API and take more care with objects lifetime and ownership. Still I find this an interesting use case.
