### ISSUE TITLE
Invalid conversion to integer running under WebAssembly

### ISSUE THREAD

**Issue by sponge** [munificent/wren#550]
I'm a noob with WASM here, but I'm trying to compile my program that uses Wren with Emscripten. It successfully runs when compiling under debug (but running the final emcc step with -O2), but I get a runtime error on Release. I'm unable to figure out how to break at the problematic code, but I do have a stack:

```
exception thrown: RuntimeError: invalid conversion to integer,_addConstant@http://localhost:8000/engine.js:959645:1
_classDefinition@http://localhost:8000/engine.js:968191:1
_definition@http://localhost:8000/engine.js:965926:1
_wrenCompile@http://localhost:8000/engine.js:981613:1
_compileInModule@http://localhost:8000/engine.js:931166:1
_wrenInterpretInModule@http://localhost:8000/engine.js:931696:1
_wrenInitializeCore@http://localhost:8000/engine.js:983461:1
_wrenNewVM@http://localhost:8000/engine.js:920698:1
__Z9Wren_InitPKcS0_@http://localhost:8000/engine.js:899072:1
__ZN9WrenScene7StartupEP10ClientInfo@http://localhost:8000/engine.js:894433:1
__Z18trap_Scene_ReplaceiP5Scene@http://localhost:8000/engine.js:35096:1
__ZL4InitPvS_@http://localhost:8000/engine.js:893631:1
_main@http://localhost:8000/engine.js:72647:1
Module._main@http://localhost:8000/engine.js:11263:52
callMain@http://localhost:8000/engine.js:11447:15
doRun@http://localhost:8000/engine.js:11504:42
run/<@http://localhost:8000/engine.js:11515:7
```

I'm not able to figure out what Wren code is causing this, but I'm hoping the error and the function it's happening in might provide some clues. If anyone has any ideas of how to debug this better or get more information (or if this is even a Wren issue at all), please let me know what I can do!

**Comment by mhermier** [comment]
Try disabling NaN tagging. I'm not sure but I think wasp does not like this trick that involves lots of number/pointer conversions.

**Comment by sponge** [comment]
Yup, that did it, thanks! Closing this since it doesn't seem to be a Wren bug.
