### ISSUE TITLE
c# LoadModule callback

### ISSUE THREAD

**Issue by tstavrianos** [munificent/wren#556]
First of all, love the library.

Now, not sure if anyone has managed to get this working and might be able to point me in the right direction.
I am trying to write a .NET Core wrapper for Wren and everything is working perfectly, except the WrenLoadModuleFn callback.
I have defined the callback as a delegate: 
[UnmanagedFunctionPointer(CallingConvention.Cdecl, CharSet = CharSet.Ansi)]
public delegate IntPtr WrenLoadModuleFn(IntPtr vm, string name);
and no matter which Marshal.String... function I use when running the code, it will always crash after the string is returned to the shared library. 

Am I missing something really obvious?

I have tried to do it the same way the existing C# wrappers are doing it, but it will still crash at the same spot (even if I avoid marshaling and just return a string instead of an IntPtr).

**Comment by Banane9** [comment]
Why don't you contribute to http://github.com/Banane9/IronWren ? :D
