### ISSUE TITLE
Single comment source file raises "Unexpected token for expression".

### ISSUE THREAD

**Issue by mauvm** [munificent/wren#57]
Running a file which only contains one comment raises the following error:

```
[test.wren line 1] Error on '': Unexpected token for expression.
```

Low impact, but I guess it's worth mentioning.

**Comment by gsmaverick** [comment]
Interesting, I encountered a similar issue in the REPL and fixed it with https://github.com/munificent/wren/pull/55 but it seems like the correct fix would be in the compiler/interpreter.

**Comment by mauvm** [comment]
I believe this is the stack trace:

wren_compiler.c > wrenCompile > definition > block > statement > expression > parsePrecedence > error

**Comment by munificent** [comment]
Good catch! Fixed now.

I think you're right, @gsmaverick, that fixing it here means we don't need to fix it in the REPL anymore, so I took that back out.

**Comment by gsmaverick** [comment]
@munificent Ideally I would have done that in my PR but I couldn't get a good enough grasp of the internals yet to do it that way :)

**Comment by munificent** [comment]
That's totally OK! The set of people who currently understand Wren's internals are... all sitting on my couch right now. :)
