### ISSUE TITLE
Compile error: print possibly out of range

### ISSUE THREAD

**Issue by kaadmy** [munificent/wren#570]
When running `make` in a fresh install, I get this error:

```
src/vm/wren_compiler.c:402:36: error: ‘: ’ directive writing 2 bytes into a region of size between 1 and 159 [-Werror=format-overflow=]
   int length = sprintf(message, "%s: ", label);
                                    ^~
src/vm/wren_compiler.c:402:16: note: ‘sprintf’ output between 3 and 161 bytes into a destination of size 159
   int length = sprintf(message, "%s: ", label);
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

I can fix it by changing line 402 from
```c
int length = sprintf(message, "%s: ", label);`
```
to
```c
int length = snprintf(message, ERROR_MESSAGE_SIZE, "%s: ", label);`
```

Not sure if this is the best way to circumvent this, but this works for now.

**Comment by underscorediscovery** [comment]
related to https://github.com/munificent/wren/pull/568

**Comment by kaadmy** [comment]
Ah okay, I went through open issues beforehand but didn't notice that one. Should I close this one then?

**Comment by underscorediscovery** [comment]
probably better to keep it centralized to one discussion, so yea :) The PR discussion has a link to this thread as well now too, so it will be noted that this was filed too.
