### ISSUE TITLE
[Question] Wren releases list

### ISSUE THREAD

**Issue by michal037** [munificent/wren#573]
Hello!

Will the list of Wren releases be updated? The last release of Wren is from [21 May 2016](https://github.com/munificent/wren/releases).

**Comment by underscorediscovery** [comment]
Since wren is still in development it doesn't do releases yet. The 0.1.0 a tag is more of a checkpoint than a release. The typical workflow is to use the code from the github master tree, and update from that!

**Comment by michal037** [comment]
Thank you for your answer!
