### ISSUE TITLE
Variadic support?

### ISSUE THREAD

**Issue by paladin-t** [munificent/wren#576]
Does Wren support variadic method at either the scripting side and the C (foreign) side? I didn't see it in the document.

**Comment by minirop** [comment]
so, you need to create N methods from 0 (or 1) to N. (wren supports upto 16 parameters, IIRC)

**Comment by bjorn** [comment]
Generally the way you'd do variadic arguments in Wren is to pass in a list.

**Comment by paladin-t** [comment]
Alright, thanks.
