### ISSUE TITLE
Request: cmdline switch for syntax check only

### ISSUE THREAD

**Issue by velkyel** [munificent/wren#582]
hello,

I'm improving emacs wren-mode and for prepared flycheck hook would be nice to have a syntax checking pass only (cmdline switch) without code interpreting.  Is it possible please?

**Comment by minirop** [comment]
I don't know how easy it would be done inside the CLI, but you can do it using:
https://github.com/munificent/wren/blob/41a56446c607cae04061fe4c15fa70894ff854ee/src/vm/wren_vm.c#L1418-L1419

**Comment by velkyel** [comment]
using wrenCompileSource() looks like good start.  I'll modify my sources acoording to.
