### ISSUE TITLE
Error in code for windows

### ISSUE THREAD

**Issue by Crides** [munificent/wren#586]
Hi! When I was trying to compile wren on mingw, I get this error:
```
src/cli/path.c: In function 'absolutePrefixLength':
src/cli/path.c:78:25: error: request for member 'chars' in something not a structure or union
     if (isSeparator(path->chars[2]))
                         ^~
```

For context, the function looks like this:
```C
// Gets the length of the prefix of [path] that defines its absolute root.
//
// Returns 1 the leading "/". On Windows, also handles drive letters ("C:" or
// "C:\").
//
// If the path is not absolute, returns 0.
static size_t absolutePrefixLength(const char* path)
{
#ifdef _WIN32
  // Drive letter.
  if (isDriveLetter(path[0]) && path[1] == ':')
  {
    if (isSeparator(path->chars[2]))
    {
      // Fully absolute path.
      return 3;
    } else {
      // "Half-absolute" path like "C:", which is relative to the current
      // working directory on drive. It's absolute for our purposes.
      return 2;
    }
  }
```

So I assume that that's an error (or typo?) because `const char *` is obviously not a `struct`. I would say that `->chars` should just be deleted. But it is so small so I don't think a PR is needed.

**Comment by bjorn** [comment]
> But it is so small so I don't think a PR is needed.

Or maybe the fix is so small, you could have created a PR and skipped the creation of an issue for it. I think you should do a PR and become a proud contributor to Wren! :-)

**Comment by Crides** [comment]
Oh well, maybe you're right ... But actually I thought an issue is less significant (maybe not the right word) than a PR. And you have to make a fork and do all that stuff... But I'll follow your advice!

**Comment by munificent** [comment]
Either an issue or a PR is fine. I'm happy to take feedback in whatever form.

For Windows-specific issues in particular, PRs are nice because I don't have a Windows machine, so it's hard for me to fix those problems myself.
