### ISSUE TITLE
Unable to import modules

### ISSUE THREAD

**Issue by kaadmy** [munificent/wren#600]
I'm using the latest Git version of Wren (744147fd94febd7dae0c14f132f2dec363252a6f), and when I try to import a custom module Wren fails with the message `Error at 'TestClass': Module variable is already defined.`

I can reliably reproduce with this code:

```c

#include <stdio.h>
#include <string.h>

#include "vm/wren.h"

static const char *moduleString = "\n"
  "class TestClass {\n"
  "  static testFunction() {\n"
  "    System.print(\"Test function!\")\n"
  "  }\n"
  "}\n"
  "\n";

static const char *sourceString = "\n"
  "import \"io\" for Stdin\n"
  "import \"mytest\" for TestClass\n"
  "TestClass.testFunction()"
  "\n";

static void wrenWriteFn(WrenVM *vm, const char *text) {
  printf("%s", text);
}

static void wrenErrorFn(WrenVM *vm, WrenErrorType type, const char *module, int line, const char *message) {
  printf("Error from %s:%d: %s\n", module, line, message);
}

static char *wrenLoadModuleFn(WrenVM *vm, const char *name) {
  if(!strcmp(name, "mytest")) { return strdup(moduleString); }
  return strdup("");
}

int main(int argc, char **argv) {
  WrenConfiguration config;
  wrenInitConfiguration(&config);
  config.loadModuleFn = wrenLoadModuleFn;
  config.writeFn = wrenWriteFn;
  config.errorFn = wrenErrorFn;

  WrenVM *vm = wrenNewVM(&config);
  wrenInterpret(vm, NULL, sourceString);
}
```

The line `import "io" for Stdin` does not fail, so this appears to be an issue related to custom modules.

A previous version (at least a few weeks ago, probably 1-2 months) did not have this issue, so this seems to be a fairly recent regression.

Any help would be appreciated.

**Comment by underscorediscovery** [comment]
This thread https://github.com/munificent/wren/pull/479 has some details closer to the end, which is a recent change.
I'd check commits for a more concise description of the change (I'd look but am occupied atm).

**Comment by kaadmy** [comment]
Ah you appear to be correct, module imports seem to have changed, so therefore is failure to RTFM and not a bug. Will close this to avoid any further confusion.

**Comment by underscorediscovery** [comment]
I don't think the docs have been updated just yet but I could be wrong!

**Comment by kaadmy** [comment]
Yeah the website docs appear out of date currently.

**Comment by kaadmy** [comment]
This issue might be a bit relevant actually, I added a module resolve function
```c
static const char *wrenResolveModuleFn(WrenVM *vm, const char *importer, const char *name) {
  int length = strlen(name);

  char *newname = malloc(length + 2);
  newname[0] = '!'; // This can be anything as long as there's at least one character
  newname[1] = '\0';

  strcat(newname, name);

  return newname;
}
```

Unless I add an extra character at the start of the module name (to make it unique) Wren refuses to load it. Is this intentional or a bug?

**Comment by underscorediscovery** [comment]
I'd suggest the test folder would have all relevant cases showing the usage, and maybe @munificent is around to comment on the nature of it in master.

**Comment by kaadmy** [comment]
All the import tests in `test/` seem to use the relative form (`import "./foo" for Foo`) for single modules, and the only uses of the short form (`import "foo" for Foo`) seem to be only inside subdirectories (`import "foo/bar" for Foo`).

(Also the `importer` argument for the resolve function is a pointer to `0x20` for some reason with the statement being `import "mytest" for TestClass`), this seemed strange so I'm not sure if it's a special value or just uninitialized.

**Comment by kaadmy** [comment]
Huh, I just tested a bit more, and my 2nd latest comment seems invnalid now.

This code
```c
static const char *moduleString = "\n"
  "class TestClass {\n"
  "  static testFunction() {\n"
  "    System.print(\"Test function!\")\n"
  "  }\n"
  "}\n"
  "\n";

static const char *sourceString = "\n"
  "import \"io\" for Stdin\n"
  "import \"mytest\" for TestClass\n"
  "TestClass.testFunction()"
  "\n";

static const char *wrenResolveModuleFn(WrenVM *vm, const char *importer, const char *name) {
  int length = strlen(name);

  char *newname = malloc(length + 2);
  newname[0] = '!'; // This can be anything as long as there's at least one character                                                                                                                                                                                            
  newname[1] = '\0';

  strcat(newname, name);

  return newname;
}

static char *wrenLoadModuleFn(WrenVM *vm, const char *name) {
  if(!strcmp(name, "!mytest")) { return strdup(moduleString); }

  return strdup("");
}
```
still does not work, it seems that as long as the loadModuleFn returns a non-empty string, Wren fails to import the module for the same reason (`Error at 'TestClass': Module variable is already defined.`)

**Comment by mhermier** [comment]
Le dim. 9 sept. 2018 à 20:45, KaadmY <notifications@github.com> a écrit :

> Huh, I just tested a bit more, and my 2nd latest comment seems invnalid
> now.
>
> This code
>
> static const char *moduleString = "\n"
>   "class TestClass {\n"
>   "  static testFunction() {\n"
>   "    System.print(\"Test function!\")\n"
>   "  }\n"
>   "}\n"
>   "\n";
> static const char *sourceString = "\n"
>   "import \"io\" for Stdin\n"
>   "import \"mytest\" for TestClass\n"
>   "TestClass.testFunction()"
>   "\n";
> static const char *wrenResolveModuleFn(WrenVM *vm, const char *importer, const char *name) {
>   int length = strlen(name);
>
>   char *newname = malloc(length + 2);
>   newname[0] = '!'; // This can be anything as long as there's at least one character
>   newname[1] = '\0';
>
>   strcat(newname, name);
>
>   return newname;
> }
> static char *wrenLoadModuleFn(WrenVM *vm, const char *name) {
>   if(!strcmp(name, "!mytest")) { return strdup(moduleString); }
>
> Why the '!' here?

>
>   return strdup("");
>
> Why returning "" and not NULL? I wonder if this has no side effects trying
to load core.

**Comment by underscorediscovery** [comment]
Related to the io part:

`io` is a module in the CLI code. The VM and the CLI are distinct parts, the CLI uses the VM in the same way that you're embedding (you're embedding the VM part, not the CLI). So, that `io` module doesn't exist because you told wren vm that it doesn't (by returning null). The optional modules (random and meta) would get found if they were enabled and you return null, nothing else exists to the vm in embedding. 

You can of course bring over the bindings from the cli etc if you wanted them, though. It'd be a bit of extra work though, depending on your goals!

**Comment by kaadmy** [comment]
Ah okay, so the `io` module working properly was a bug I caused by returning an empty string and not NULL.

**Comment by kaadmy** [comment]
Did some digging, it works fine with commit b2b2b8a4e7918fd3f77af7ec6d6addeade8b90fd but fails with the next commit (fe7e56d5086134d848ad539ec97d4dcc25db3a23)

Unfortunately the failing commit is a rather large merge, so it may take time to find a specific way to fix this.

**Comment by kaadmy** [comment]
So by changing this line in my main source file from
```c
wrenInterpret(vm, NULL, sourceString);
```
to
```c
wrenInterpret(vm, "main", sourceString);
```
all the import issues seem to no longer exist. I just checked the existing tests and this seems to be the proper method, and I was using wrenInterpret incorrectly.

**Comment by underscorediscovery** [comment]
glad you figured that out, we should probably add some assertions or validations about what that parameter being null means.
