### ISSUE TITLE
Proposition for a fork.

### ISSUE THREAD

**Issue by mhermier** [munificent/wren#623]
Hi,

I'm really considering to do a fork of the project under the name 'canary'. As the situation goes, wren is stalling with a pile of issues accumulating.

The short plan is to have a decent vm. Probably not the fastest, but with less bugs, and with a revisited design. At long term there will be a clear separation of code path with rebranding, and code style changes.

The big aim is to make the language and vm evoluate, and even consider to support other languages. 

But first I would like to see if the community is interested?

**Comment by masrourmouad** [comment]
please if you are doing a fork, change how function are made, i will give my star if you will make the change, thanks

**Comment by CodogoFreddie** [comment]
For what It's worth, I'd really hate to see a fork, I think wren's built up a lot of momentum despite being quite incomplete and it would be a real shame to split the comunity.

I wonder if @munificent would consider allowing someone else write permission to the repo? I know it's been a personal project for a long time, but it's not fair for us to expect him to act as a full-time maintainer for a large codebase while also having a full time job and other hobbies.

**Comment by masrourmouad** [comment]
@CodogoFreddie do you like the current way that functions work

**Comment by mhermier** [comment]
It will surely change but I still don't know how.
One thing I would also like to change is the general naming conventions. I toyed a lot with the language and the Capital letter convention for global scope is a real anoyance when you have to do/use/export functions.

**Comment by masrourmouad** [comment]
The only thing that prevant me from programming in Wren is how function woks; a fork should add more contents and functionality.

**Comment by mhermier** [comment]
How function works or how they are declared ?

**Comment by masrourmouad** [comment]
who function are declared

**Comment by mhermier** [comment]
Not sure about the details, but I really like the [Jai](https://github.com/BSVino/JaiPrimer/blob/master/JaiPrimer.md) way to declare functions. But unfortunately it requires a more complex compiler. So probably any solution till the compiler get changed might be temporary.

**Comment by masrourmouad** [comment]
Jai have a nice one , i would like a more basic function declaration style like:
func add (a, b, c) {
    return a + b + c;
}

**Comment by masrourmouad** [comment]
true, Wren for me will  have a great future, helping developers get started by facilitating Wren will help.

**Comment by jube** [comment]
I am against a fork. Wren is a simple language, it has to remain simple. That is the philosophy of the language. If you want something more complex, you do not want Wren, you want Lua ou something else.

**Comment by masrourmouad** [comment]
Our goal is to make wren better

**Comment by jube** [comment]
@mhermier: Like I said, you want something with more features, not Wren, and that's totally fine. I use Wren because of its extreme simplicity, I do not need a I/O library, I only need the core modules and nothing else. So go for "canary" as you name it, but leave Wren alone ;)

@masrourmouad: Wren as a library/executable has some bugs, like any other software, and can be improved but Wren as a langage does not need new features, it's already perfect for its niche use case.

**Comment by mhermier** [comment]
@jube: It is not that I want paticularly add many more features (at least not in the core langage). But if you want to do stuff with the modules, some plumbing, fixes and langage polish need to be made.

**Comment by munificent** [comment]
Hi, @mhermier. Thanks for starting this thread.

I've obviously not been putting much time into Wren for a while. I do still like it and enjoy hacking on it, but the things I need to work on (re-entrancy, mainly) require a level of time and focus that I haven't been able to find lately.

It may be that I'm holding Wren back and the best thing I could do for its success is get myself out of the way. Would you and/or @underscorediscovery be interested in having stewardship over the project?

**Comment by jube** [comment]
Why not creating a team of maintainers?

**Comment by munificent** [comment]
Eventually, yeah, I think a whole team is great. But especially for a minimal language, I think it's critical to have one or two people responsible for owning the vision and keeping things small and clean.

**Comment by jyaif** [comment]
@munificent 
Thanks for creating this awesome project. Wren does so many things right I can totally see it replacing Lua for game scripting!

Complex changes like re-entrancy requires the attention of someone that has the "vision", but lightweight changes (documentation improvements / small bugs / tiny non-controversial features) can be handled by somebody else.
For example, https://github.com/munificent/wren/pull/610 and https://github.com/munificent/wren/pull/611 really don't need to linger for months :-)

I suggest starting by giving someone a 2 months trial run with the direction "only merge pull requests that fix the documentation and comments".

And yes, I volunteer for such a role.

**Comment by jube** [comment]
I would like to volunteer as one of the "keepers of the temple".

**Comment by munificent** [comment]
I started a discussion about how to handle this here: https://groups.google.com/forum/#!topic/wren-lang/cMUwij-NIn0

**Comment by mhermier** [comment]
The fork is effective an running using the name "canary".
