### ISSUE TITLE
Wren without UV?

### ISSUE THREAD

**Issue by IngwiePhoenix** [munificent/wren#626]
I am trying to find myself a nice scripting language for my application and came across Wren. Well, the app I am trying to make is meant to be as small as possible - and it doesn't ever really depend on libuv. So, I would like to cut it out from wren and just use Wren as a scripting engine and decide exactly which things I want it to have (which FS implementation, for instance).

So how do I compile Wren plainly without libuv? Which `gcc` commands would I need to run?

Thanks!

**Comment by underscorediscovery** [comment]
Wren is built as a VM first, then a CLI application that uses the VM to provide some tools. The CLI is the one that uses UV. The vm is not.

You could try the embedding documentation, http://wren.io/embedding/
that should answer the questions you might have about using the vm directly.

**Comment by IngwiePhoenix** [comment]
Oh wow, the vm seems incredibly naked from what I see.

> The VM itself does not know how to talk to the file system (...).

That is very much what I want. Thank you! :)
