### ISSUE TITLE
Number test failures

### ISSUE THREAD

**Issue by edsrzf** [munificent/wren#65]
When I run `make test`, I get a test failure:

    $ make test
    FAIL: test/number/divide.wren     
          Expected output "nan" on line 7 and got "-nan".
          Expected output "nan" on line 8 and got "-nan".
          Expected output "nan" on line 11 and got "-nan".
          Expected output "nan" on line 12 and got "-nan".

The relevant test cases:

    IO.print(0 / 0)         // expect: nan
    IO.print(-0 / 0)        // expect: nan
    IO.print(0 / -0)        // expect: nan
    IO.print(-0 / -0)       // expect: nan

Lua 5.2.3 gives the same -nan results, for what it's worth.

**Comment by edsrzf** [comment]
I noticed that Travis CI is having the same problem. [Example](https://travis-ci.org/munificent/wren/jobs/45962924)

**Comment by munificent** [comment]
Yup, thanks for filing the tracking bug! This is on my mental TODO list and not it's on the official one. :) I'll take a look.

**Comment by munificent** [comment]
Apparently the behavior of libc isn't fully specified here and some versions of it do different things on signed nan. See: http://stackoverflow.com/questions/3772835/getting-a-negative-nan-on-g-4-4-3-is-this-standard
