### ISSUE TITLE
SegFault when overridding toString

### ISSUE THREAD

**Issue by Calamari** [munificent/wren#67]
Hello.

Just getting warm with the wren language, and I must say: It's neat. I just do useless playaround stuff with it, and came across the following problem:

When you try running the following "program" you will get a `Segmentation Fault: 11`.

```wren
class My {
  toString { 3 }
}

var my = new My

IO.print(my)
```

Of course the problem is, that I return a non-string in the toString method, if I would write { "3"} then all would work as expected. Still, I think there should be a warning or error raised, and not abort with a SegFault.

What do you think?

**Comment by munificent** [comment]
Yes, this is totally a bug!

It's coming from a limitation in the current still-very-much-in-progress embedding API. Right now, the API doesn't give you a way to generate a runtime error, which is what it should do when the result of `toString` isn't a string.

Thanks for filing this!
