### ISSUE TITLE
Proposal: Module classes

### ISSUE THREAD

**Issue by munificent** [munificent/wren#79]
OK, I've got a strawman proposal for how to handle modules I'd like to get feedback on. Here's my high level goals:

* (0) The zeroth goal, as always, is **do something *simple*.** Wren is tiny and minimal. Tiny tiny tiny.

* (1) **Avoid a monolithic global scope.** If two unrelated modules both define the same name at the top level, I'd like that to not cause problems. "Include"-style module systems where importing a module basically means "run it in the top level scope" feel dirty to me. That being said, they do satisfy the zeroth goal.

* (2) This is more a given than a goal, but **the physical location of modules is up to the embedder.** In Wren, you'd just specify a "logical" name for a module to import. How that gets mapped to the file system (or whatever) is up to the embedder. Of course, the command-line embedder that comes with Wren will have a, hopefully sane, implemented behavior for this.

* (3) **Handle shared imports.** Main imports A and B which both import C. This should only cause C to be loaded and executed once. Since loading a module may have side-effects, I think this is a given.

* (4) **Handle circular imports.** This is a bit more contentious in a scripting language. But statically typed languages almost invariably support this and it is handy. In Dart, I have cyclic imports *all the time*.

    It's more important in a static language because you often need to import a module solely to be able to use its names in type annotations. Wren isn't statically typed, but I intend to write a static analysis tool for it. (Think like dialyzer for Erlang.) So I'd like to not rule out circular imports if possible.

* (5) **Still provide compile errors for undefined globals.** Right now, an undefined name is detected and reported at compile time. I really like that. One easy way to handle circular imports is to just implicitly define globals. Then it doesn't matter which order imports are loaded as much as long as you don't *use* a name until after it's handled.

   But, if possible, I'd like to not do this. I like compile errors for my dumb typos.

* (6) **Let the importer control the name(s) bound from the imported module.** The person defining the module doesn't know what other names may be in scope when their module is used. Only the consumer knows that, so ideally the consumer has some control here. This is why, for example, Python has "import as".

### Strawman #1 - Lua-style module objects

Lua has a neat system. The `require()` function loads a script and *returns the value returned by that script.* You use it like:

```lua
local someModule = require('someModule')
```

So you control the local "prefix" used to access the module, and the module is really just an object. Super simple. In Lua, the object returned is usually a table. Wren isn't table-based, so instead this would naturally be an instance, or possibly a class object. Either works.

We'd probably want a little syntax sugar for imports, but as a first pass, we could start with that. Add a static method that loads a script, evaluates it, and gets the value it returns.

You bind the result of that to a local variable and you're good to go. For example, you could have a 2d vector module like:

```dart
class Vector {
  new(x, y) {
    _x = x
    _y = y
  }

  // ...
}

return Vector
```

I'm not sure what to hang the import method off of so for—just for this doc— I'll just hang it off IO. You could import the above module like:

```dart
var Vector = IO.import('vector')

var v = new Vector(1, 2)
```

For the case where a module exposes a single class, I think this works well. For modules that want to expose constants and other stuff, they'd basically have to hang them off the class as static getters.

Is that gross? Slow?

This trivially addresses goals 0, 1, 2 and has a nice solution for 6. It also addresses 5 with the caveat that you basically lose compile errors for imported "names". Since those become dynamically dispatched getters off the one imported instance, they aren't checked at compile time any more.

For example:

```dart
// vector.wren
class Vector {
  static origin { new Vector(0, 0) }
}

return Vector
```

```dart
// main.wren
var Vector = IO.import('vector')

Vector.origon
```

Here, we mispelled `origin`, but the compiler won't help. But it still catches other name errors for lexical names you define.

Goal 3, shared imports, is pretty simple. We just keep a table of objects returned by previously loaded modules and return the previous one if the same name is requested. That's what pretty much every language does.

OK, what about circular imports?

Here's a pair of modules that should work:

```dart
// main.wren
var Other = IO.import('other')

class Main {
  static inMain {
    IO.print("inMain")
  }
}

Other.inOther

return Main
```

and:

```dart
// other.wren
var Main = IO.import('main')

class Other {
  static inOther {
    IO.print("inOther")
    Main.inMain
  }
}

return Other
```

What's the execution model here?

1. Start executing main.wren.
2. Get to the import and pause main.
3. Start executing other.wren.
4. Get to the import

At this point, node can do something nice. It just returns an empty module object for main. When main is resumed, it will *imperatively add stuff to that object* instead of *creating it*. So it can just return the shell object. Then, by the time `Other.inOther` is called, main has added inMain to it and everything is fine.

We can't do that in Wren since classes are created monolithically. We'd have to do something tricky to break the cycle like have `import('main')` return a proxy, or have the VM track the global it gets assigned to and reassign that after main is done.

### Strawman #2 - Module classes

We can't just jack Lua's solution into Wren without some kind of VM changes to handle cycles. Let's try adding a *little* bit of special sauce.

The basic idea is that each module implicitly gets a class created before the module is loaded. When you import the module, that class is the object that is returned by `import()`.

The clever bit is that we let you add methods to it in the body of the module. I'm thinking something like:

```dart
// main.wren
var Other = IO.import('other')

module Main {
  static inMain {
    IO.print("inMain")
  }
}

Other.inOther

```

and:

```dart
// other.wren
var Main = IO.import('main')

module Other {
  static inOther {
    IO.print("inOther")
    Main.inMain
  }
}
```

The classes have been replaced with `module` which would be a reserved word meaning "add these methods to the module's implicit class". We could even have the VM implicitly *instantiate* that class and return the instance so that you don't have to make everything static. Actually, no. Because often you would want your module to be a constructible class.

OK, so now the execution model is:

1. Start executing main.wren.
2. That creates a class for the main module and stores it in the module table.
3. Get to the `import('other')` and pause main.
4. Start executing other.wren.
5. That creates a class for the other module and stores it in the module table.
6. Get to the `import('main')`. Main is already in the module table, so just
   return it.
7. Get to the module definition in other.
8. Define the `inOther` method on other's module class.
9. Finish other.
10. Resume main.
11. Get to the module definition in main.
12. Define the `inMain` method on main's module class.
13. Call `Other.inOther`. It's fine because it's defined now.
14. That calls `Main.inMain`. Also fine.

So... I think this works? The two pieces of VM infrastructure (aside from new stuff like the module table and import functionality) we need are:

1. That ability to pause a script while we execute another.
2. The ability to add new methods to an existing class.

Fibers already give us #1. And the VM already supports #2 internally. There's just no syntax to allow monkey-patching.

Another option is to actually add a syntax to monkey patch a class. Then, as long as you knew what the name of your module class was, you could just extend it:

```dart
// other.wren
var Main = IO.import('main')

extend class Other {
  static inOther {
    IO.print("inOther")
    Main.inMain
  }
}
```

Even though the importer controls the name of the variable that they bind the module class to, it's still important for the module class itself to have a name since it shows up in stack traces, error messages, etc.

Thoughts?

**Comment by munificent** [comment]
Even without explicit support for nested classes, you could still do this, like so:

```dart
class A {}
class B {}

module Both {
  static a { A }
  static b { B }
}
```

It's definitely kind of ugly.

I have thought about nested classes for a while, and in fact about more directly making modules equivalent to classes. That's one of the key ideas in Gilad Bracha's Newspeak and I think it's got a lot going for it. It also lines up well with Wren's heavily class-based philosophy.

The natural endpoint of that line of thinking is that the top level of a module just *is* a class. I've considered that a little bit, but I haven't spent the time to sit down and think it all the way through to see if it makes sense.

One thing it implies is that "top-level" variables are properties on that outermost class, which means they're dynamically dispatched. That handles things like mutual recursion at the top level well (which currently isn't handled by Wren), but it means giving up errors on typos for top-level names.

I'll try to spend some time working through the ramifications and see if that makes sense.

**Comment by EvanHahn** [comment]
Why can't the execution model for module classes work for the Lua-style method? I personally like the Lua style better than module classes, for what it's worth.

**Comment by munificent** [comment]
Lua doesn't support cyclic requires at all. You can sort of work around it, but [it's pretty hacky](http://stackoverflow.com/a/13964765/9457). I'm hoping for something that works a little more gracefully than that.

**Comment by zeckalpha** [comment]
Should alternate Strawmen go here or as separate issues? I've got a header file proposal, inspired by SML modules/structures/functors.

**Comment by munificent** [comment]
> Should alternate Strawmen go here or as separate issues?

Yes, that would be great!

> I've got a header file proposal, inspired by SML modules/structures/signatures/functors.

I'm definitely intrigued.

**Comment by zeckalpha** [comment]
Would you be able to have private methods under this proposal?

**Comment by munificent** [comment]
The module can definitely have private *variables*. Variables at the top level are still lexically scoped to the module and wouldn't be exported.

Wren doesn't have any concept of private methods, though, so if you add any methods to the module class itself, they'd be private.

**Comment by emeseles** [comment]
What about a late binding model. Instead of a piece of code specifying what it needs, its needs are known at compile time to bytecode. It could be compiled within a 'scope' that was defined when the code was loaded from a main,

new Scope("Vector", "Matrix", "HobermanSphere");
new Scope("subproject/*")

Wren loads up all the named stuff, with wildcards since as you said, logical names work best and then runs the code in that 'scope'. Fibers can therefore have different scopes entirely or a scope can be reused across fibers if appropriate.

HobermanSphere does not need to specify how or where it gets Vector and Matrix from, it just assumes there will be classes with those names visible in its scope, otherwise it'll get a runtime error when the scope tries to do the final binding. As such, you'd know 99% of the time if you were missing a library the moment you try to run your program.

Thought it was worth offering the idea of flipping the module discussion on its head.

**Comment by munificent** [comment]
I'm sorry, but I had trouble following that. Can you walk me through how you envision it loading a couple of modules?

**Comment by emeseles** [comment]
Consider each Scope instance like a Smalltalk 'mini image'. You define a scope and give it (several) files to load. At the end of this it will bind the globals for that scope. An example main might look like this:

// project/geometry/Vector.wren
class Vector2D {
   new(x, y) {
    _x = x
    _y = y
   }
   x { return _x }
   y { return _y }
   to(end) {
     return new LineSegment(this, end)
   }
}

// project/geometry/LineSegment.wren
class LineSegment {
    new(start, stop) {
     _start = start
     _stop = stop
    }
    start { return _start }
    stop { return _stop }
    direction { return _stop - _start }
    lengthSquared { return this.direction.x * this.direction.x + this.direction.y * this.direction.y }
    length { return this.lengthSquared.sqrt }
    midpoint { return (this.length / 2) + _start }
    excuseForCircularDependency { return new Vector2D(_start.x, _start.y) }
}

// main.wren
var mainProject = new Scope("project/**")
mainProject.call {
    var unitLength = new Vector2D(0, 0).to(Vector2D(1, 0)).length
    IO.print(unitLength)
}

Because the Scope is given file pattern(s) to determine what to load, you can replace any individual file with your own variant at any point, when it would be most advantageous. Otherwise, within a scope, all things are considered 'global' to that scope.

This would double as not only the way to 'include' code, but also the scope that code is resolved in.

// more main.wren
var experimentalProject = new Scope("project/geometry/LineSegment", "experiment/superFastVector2D.wren")
experimentalProject.call {
    var unitLength = new Vector2D(0, 0).to(Vector2D(1, 0)).length
    IO.print(unitLength)
}

Here LineSegment is the same code from both scopes, but the experimentalProject and mainProject use a different Vector2D. This allows the top-level to specify what is and is not in a scope. In this scenario I can compare how the two different implementations of Vector2D compare. They cannot both be loaded in to the same scope at once however, that'd be a duplicate binding error.

**Comment by munificent** [comment]
Ah, I think I understand it more now, thank you!

> ```dart
> var mainProject = new Scope("project/**")
> ```

Is the idea here that it would load *everything* in that directory? Or just that *if it needs something*, it looks there? If the latter, how does it determine what's actually needed?

I do like the idea of being able to separate how an import is physically located from the logical identifier that's being requested.

Currently, I'm working on implementing #122 instead of this proposal. Since it makes imports statements, I believe we could retrofit that same idea there if needed.

**Comment by emeseles** [comment]
Personally, I'd just have it load everything in the list. If Wren supports the ability to add new methods to an existing class, then this'd be useful. You could lazily compile the class contents so that the identifiers are all known, but would that really save much time? you do boast a fast single-pass compiler for Wren after all.

One thing that is missing from this proposal is a way to initialise code based on other code. Having a scope-level event of "Everything is now loaded, you may initialise" on a per-class (or per-module) basis would be required, eg:

// FunkyGraphics.wren
OpenGL.loaded {
   ...init resources...
}

This'd be the only explicit dependency needed though.

**Comment by munificent** [comment]
Closing this because modules are in now! I ended up going with a slightly different approach since I realized while implementing that it's easier to work with a module's top-level variables as variables instead of trying to make something like a first-class modules.
