### ISSUE TITLE
Optional stdlib / cookbook

### ISSUE THREAD

**Issue by zeckalpha** [munificent/wren#86]
I know the point is to keep Wren core small, but perhaps an opt-in standard library with broader features would be useful. This could be implemented as more of a cookbook, including only the needed portions when embedding.

**Comment by munificent** [comment]
Yeah, it's sort of set up that way now. An embedder can optionally not include IO, for example. I agree a larger "standard" library that's written in pure Wren code would be good. Whether it's literally bundled with Wren or is just "third party" and managed by the module system is an open question. :)
