### ISSUE TITLE
Parse of "i-1" is space-sensitive

### ISSUE THREAD

**Issue by edsrzf** [munificent/wren#93]
The parse of `i - 1` varies depending on whether or not there's a space before the `1`. If there's no space, it's interpreted as "negative one" and causes confusing parse failures:

```dart
var i = 1
// These would parse as i (-1) and give the error: Error on '-1': Expect ')' after arguments.
//IO.print(i-1)
//IO.print(i -1)

// These are fine
IO.print(i - 1)
IO.print(i- 1)
```

I can accept that there might be one preferred way to write it, but this doesn't seem correct.

**Comment by munificent** [comment]
Ah, this was a mistake on my part. I think we just need to remove support for negative number literals. Instead of tokenizing `-1` as a number, it should be two tokens, `-` and `1`. It's a pretty simply change to `nextToken()` if you'd like to fix this. The main effort would just be writing a test or two (which you pretty much did here in the bug). :)

**Comment by edsrzf** [comment]
I originally thought it would basically just be removing [these lines](https://github.com/munificent/wren/blob/master/src/wren_compiler.c#L755-L758), but that didn't work because `-16.sqrt` started being parsed as `-(16.sqrt)`, which is not what we want.

So either I'm looking in the wrong place, or we need to change the parser also.

**Comment by munificent** [comment]
> being parsed as -(16.sqrt), which is not what we want.

Actually, strangely enough, I think that probably *is* what we want. In both JavaScript and Dart, the `.` does have higher precedence so you get the above parse. It's consistent with how this is parsed:

```js
-foo.bar
```

Here, you'd expect the `-` to apply to the result of `foo.bar`, so JS and Dart just do the same thing when `foo` is a number literal instead. Ruby is a bit smarter about this, but Ruby's grammar is also notoriously hairy, so I don't know if we want to try to ape them.

(Whatever we decide, this is also a good thing to add a test for!)

**Comment by edsrzf** [comment]
Okay, I'll put in a pull request for doing it that way. It will change some existing test cases.

**Comment by munificent** [comment]
Looks great!
